version: 2

updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /apis
      - /runtime
      - /generators/v1/*
      - /providers/v1/*
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: github.com/external-secrets/external-secrets
      - dependency-name: github.com/external-secrets/external-secrets/*

  - package-ecosystem: gomod
    directory: /e2e
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      e2e-go-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: github.com/external-secrets/external-secrets
      - dependency-name: github.com/external-secrets/external-secrets/*

  - package-ecosystem: gomod
    directories:
      - /hack/tools/*
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      tool-go-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: github.com/external-secrets/external-secrets
      - dependency-name: github.com/external-secrets/external-secrets/*
