# This file has the syntax of VOUCH: https://github.com/mitchellh/vouch
# Always add the communication link to a line.
# First warnings are commented lines in the form `#-<username> <date of warning> <link to warning>`
# Temporary bans are in the form `-<username> <date of warning> <link to warning> <date of temporary ban> <link to temporary ban notice>`
# Restore from temp ban are in the form: `#-<username> <date of warning> <link to warning> <date of temporary ban> <link to temporary ban notice>`
# Permanent bans are in the form `-<username> <date of warning> <link to warning> <date of temporary ban> <link to ban notice> <date of permanent ban> <link to ban notice>`
# It is easy to figure out if you are in a temp ban, count the amount of http: links for a user

#-dbinger 20260717 https://github.com/external-secrets/external-secrets/pull/6649#issuecomment-5005148594
-sanchpet 20260809 https://github.com/external-secrets/external-secrets/pull/6814#issuecomment-5233523479
-mail2sudheerobbu-oss 20260809 https://github.com/external-secrets/external-secrets/pull/6789#issuecomment-5233438543
#-vianmangal 20260819 https://github.com/external-secrets/external-secrets/pull/6781#issuecomment-5339938023
