FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:6825946f10e8c81586fa7815c4f06016af05cfc231d921ec9699402a6655d201
ARG TARGETOS
ARG TARGETARCH
COPY bin/external-secrets-${TARGETOS}-${TARGETARCH} /bin/external-secrets

RUN microdnf update

# Run as UID for nobody
USER 65534

ENTRYPOINT ["/bin/external-secrets"]
