/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by providers/v2/hack/generate-provider-main.go. DO NOT EDIT.

package main

import (
	"flag"
	"log"

	genv1alpha1 "github.com/external-secrets/external-secrets/apis/generators/v1alpha1"
	fakev2alpha1 "github.com/external-secrets/external-secrets/apis/provider/fake/v2alpha1"
	genpb "github.com/external-secrets/external-secrets/proto/generator"
	pb "github.com/external-secrets/external-secrets/proto/provider"
	"github.com/external-secrets/external-secrets/providers/v2/adapter"
	adaptergenerator "github.com/external-secrets/external-secrets/providers/v2/adapter/generator"
	adapterstore "github.com/external-secrets/external-secrets/providers/v2/adapter/store"
	grpcserver "github.com/external-secrets/external-secrets/providers/v2/common/grpc/server"
	generator "github.com/external-secrets/external-secrets/providers/v2/fake/generator"
	store "github.com/external-secrets/external-secrets/providers/v2/fake/store"
	"google.golang.org/grpc"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/config"
)

var (
	port      = flag.Int("port", 8080, "The server port")
	enableTLS = flag.Bool("enable-tls", true, "Enable TLS/mTLS for gRPC server")
	verbose   = flag.Bool("verbose", false, "Enable verbose connection-level debugging")
)

func main() {
	flag.Parse()

	log.Printf("starting on port %d (TLS: %v, Verbose: %v)", *port, *enableTLS, *verbose)

	// Create Kubernetes client (required by adapter)
	scheme := runtime.NewScheme()
	_ = clientgoscheme.AddToScheme(scheme)
	_ = fakev2alpha1.AddToScheme(scheme)
	_ = genv1alpha1.AddToScheme(scheme)

	cfg, err := config.GetConfig()
	if err != nil {
		log.Fatalf("Failed to get kubeconfig: %v", err)
	}

	kubeClient, err := client.New(cfg, client.Options{Scheme: scheme})
	if err != nil {
		log.Fatalf("Failed to create Kubernetes client: %v", err)
	}
	// Setup v1 provider(s)
	v1Provider0 := store.NewProvider()
	providerMapping := adapterstore.ProviderMapping{
		schema.GroupVersionKind{
			Group:   "provider.external-secrets.io",
			Version: "v2alpha1",
			Kind:    "Fake",
		}: v1Provider0,
	}

	specMapper := GetSpecMapper(kubeClient)
	// Setup v1 generator(s)
	generatorMapping := adaptergenerator.Mapping{
		schema.GroupVersionKind{
			Group:   "generators.external-secrets.io",
			Version: "v1alpha1",
			Kind:    "Fake",
		}: generator.NewGenerator(),
	}
	adapterServer := adapter.NewServer(kubeClient, scheme, providerMapping, specMapper, generatorMapping)

	log.Printf("[PROVIDER] Using v1 Fake Provider provider with generators wrapped with v2 adapter")
	if err := grpcserver.RunProviderServer(grpcserver.RuntimeOptions{
		ProviderName: "Fake Provider",
		Port:         *port,
		EnableTLS:    *enableTLS,
		Verbose:      *verbose,
		Register: func(registrar grpc.ServiceRegistrar) {
			pb.RegisterSecretStoreProviderServer(registrar, adapterServer)
			genpb.RegisterGeneratorProviderServer(registrar, adapterServer)
		},
	}); err != nil {
		log.Fatalf("Failed to run provider server: %q", err.Error())
	}
}
