/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AzureACRManagedIdentityAuthApplyConfiguration represents a declarative configuration of the AzureACRManagedIdentityAuth type for use
// with apply.
//
// AzureACRManagedIdentityAuth defines the configuration for using Azure Managed Identity authentication.
type AzureACRManagedIdentityAuthApplyConfiguration struct {
	// If multiple Managed Identity is assigned to the pod, you can select the one to be used
	IdentityID *string `json:"identityId,omitempty"`
}

// AzureACRManagedIdentityAuthApplyConfiguration constructs a declarative configuration of the AzureACRManagedIdentityAuth type for use with
// apply.
func AzureACRManagedIdentityAuth() *AzureACRManagedIdentityAuthApplyConfiguration {
	return &AzureACRManagedIdentityAuthApplyConfiguration{}
}

// WithIdentityID sets the IdentityID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdentityID field is set to the value of the last call.
func (b *AzureACRManagedIdentityAuthApplyConfiguration) WithIdentityID(value string) *AzureACRManagedIdentityAuthApplyConfiguration {
	b.IdentityID = &value
	return b
}
