/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// AzureACRServicePrincipalAuthSecretRefApplyConfiguration represents a declarative configuration of the AzureACRServicePrincipalAuthSecretRef type for use
// with apply.
//
// AzureACRServicePrincipalAuthSecretRef defines the secret references for Azure Service Principal authentication.
// It uses static credentials stored in a Kind=Secret.
type AzureACRServicePrincipalAuthSecretRefApplyConfiguration struct {
	// The Azure clientId of the service principle used for authentication.
	ClientID *v1.SecretKeySelector `json:"clientId,omitempty"`
	// The Azure ClientSecret of the service principle used for authentication.
	ClientSecret *v1.SecretKeySelector `json:"clientSecret,omitempty"`
}

// AzureACRServicePrincipalAuthSecretRefApplyConfiguration constructs a declarative configuration of the AzureACRServicePrincipalAuthSecretRef type for use with
// apply.
func AzureACRServicePrincipalAuthSecretRef() *AzureACRServicePrincipalAuthSecretRefApplyConfiguration {
	return &AzureACRServicePrincipalAuthSecretRefApplyConfiguration{}
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *AzureACRServicePrincipalAuthSecretRefApplyConfiguration) WithClientID(value v1.SecretKeySelector) *AzureACRServicePrincipalAuthSecretRefApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *AzureACRServicePrincipalAuthSecretRefApplyConfiguration) WithClientSecret(value v1.SecretKeySelector) *AzureACRServicePrincipalAuthSecretRefApplyConfiguration {
	b.ClientSecret = &value
	return b
}
