/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	generatorsv1alpha1 "github.com/external-secrets/external-secrets/apis/generators/v1alpha1"
)

// ClusterGeneratorSpecApplyConfiguration represents a declarative configuration of the ClusterGeneratorSpec type for use
// with apply.
//
// ClusterGeneratorSpec defines the desired state of a ClusterGenerator.
type ClusterGeneratorSpecApplyConfiguration struct {
	// Kind the kind of this generator.
	Kind *generatorsv1alpha1.GeneratorKind `json:"kind,omitempty"`
	// Generator the spec for this generator, must match the kind.
	Generator *GeneratorSpecApplyConfiguration `json:"generator,omitempty"`
}

// ClusterGeneratorSpecApplyConfiguration constructs a declarative configuration of the ClusterGeneratorSpec type for use with
// apply.
func ClusterGeneratorSpec() *ClusterGeneratorSpecApplyConfiguration {
	return &ClusterGeneratorSpecApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ClusterGeneratorSpecApplyConfiguration) WithKind(value generatorsv1alpha1.GeneratorKind) *ClusterGeneratorSpecApplyConfiguration {
	b.Kind = &value
	return b
}

// WithGenerator sets the Generator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generator field is set to the value of the last call.
func (b *ClusterGeneratorSpecApplyConfiguration) WithGenerator(value *GeneratorSpecApplyConfiguration) *ClusterGeneratorSpecApplyConfiguration {
	b.Generator = value
	return b
}
