/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GeneratorStateSpecApplyConfiguration represents a declarative configuration of the GeneratorStateSpec type for use
// with apply.
//
// GeneratorStateSpec defines the desired state of a generator state resource.
type GeneratorStateSpecApplyConfiguration struct {
	// GarbageCollectionDeadline is the time after which the generator state
	// will be deleted.
	// It is set by the controller which creates the generator state and
	// can be set configured by the user.
	// If the garbage collection deadline is not set the generator state will not be deleted.
	GarbageCollectionDeadline *v1.Time `json:"garbageCollectionDeadline,omitempty"`
	// Resource is the generator manifest that produced the state.
	// It is a snapshot of the generator manifest at the time the state was produced.
	// This manifest will be used to delete the resource. Any configuration that is referenced
	// in the manifest should be available at the time of garbage collection. If that is not the case deletion will
	// be blocked by a finalizer.
	Resource *apiextensionsv1.JSON `json:"resource,omitempty"`
	// State is the state that was produced by the generator implementation.
	State *apiextensionsv1.JSON `json:"state,omitempty"`
}

// GeneratorStateSpecApplyConfiguration constructs a declarative configuration of the GeneratorStateSpec type for use with
// apply.
func GeneratorStateSpec() *GeneratorStateSpecApplyConfiguration {
	return &GeneratorStateSpecApplyConfiguration{}
}

// WithGarbageCollectionDeadline sets the GarbageCollectionDeadline field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GarbageCollectionDeadline field is set to the value of the last call.
func (b *GeneratorStateSpecApplyConfiguration) WithGarbageCollectionDeadline(value v1.Time) *GeneratorStateSpecApplyConfiguration {
	b.GarbageCollectionDeadline = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *GeneratorStateSpecApplyConfiguration) WithResource(value apiextensionsv1.JSON) *GeneratorStateSpecApplyConfiguration {
	b.Resource = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *GeneratorStateSpecApplyConfiguration) WithState(value apiextensionsv1.JSON) *GeneratorStateSpecApplyConfiguration {
	b.State = &value
	return b
}
