/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RequestParametersApplyConfiguration represents a declarative configuration of the RequestParameters type for use
// with apply.
//
// RequestParameters contains parameters that can be passed to the STS service.
type RequestParametersApplyConfiguration struct {
	SessionDuration *int32 `json:"sessionDuration,omitempty"`
	// SerialNumber is the identification number of the MFA device that is associated with the IAM user who is making
	// the GetSessionToken call.
	// Possible values: hardware device (such as GAHT12345678) or an Amazon Resource Name (ARN) for a virtual device
	// (such as arn:aws:iam::123456789012:mfa/user)
	SerialNumber *string `json:"serialNumber,omitempty"`
	// TokenCode is the value provided by the MFA device, if MFA is required.
	TokenCode *string `json:"tokenCode,omitempty"`
}

// RequestParametersApplyConfiguration constructs a declarative configuration of the RequestParameters type for use with
// apply.
func RequestParameters() *RequestParametersApplyConfiguration {
	return &RequestParametersApplyConfiguration{}
}

// WithSessionDuration sets the SessionDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionDuration field is set to the value of the last call.
func (b *RequestParametersApplyConfiguration) WithSessionDuration(value int32) *RequestParametersApplyConfiguration {
	b.SessionDuration = &value
	return b
}

// WithSerialNumber sets the SerialNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SerialNumber field is set to the value of the last call.
func (b *RequestParametersApplyConfiguration) WithSerialNumber(value string) *RequestParametersApplyConfiguration {
	b.SerialNumber = &value
	return b
}

// WithTokenCode sets the TokenCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenCode field is set to the value of the last call.
func (b *RequestParametersApplyConfiguration) WithTokenCode(value string) *RequestParametersApplyConfiguration {
	b.TokenCode = &value
	return b
}
