/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	externalsecretsv1 "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
	generatorsv1alpha1 "github.com/external-secrets/external-secrets/apis/generators/v1alpha1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// VaultDynamicSecretSpecApplyConfiguration represents a declarative configuration of the VaultDynamicSecretSpec type for use
// with apply.
//
// VaultDynamicSecretSpec defines the desired spec of VaultDynamicSecret.
type VaultDynamicSecretSpecApplyConfiguration struct {
	// Used to select the correct ESO controller (think: ingress.ingressClassName)
	// The ESO controller is instantiated with a specific controller name and filters VDS based on this property
	Controller *string `json:"controller,omitempty"`
	// Vault API method to use (GET/POST/other)
	Method *string `json:"method,omitempty"`
	// Parameters to pass to Vault write (for non-GET methods)
	Parameters *v1.JSON `json:"parameters,omitempty"`
	// GetParameters are query-string parameters passed to Vault on GET calls.
	// Each key may map to multiple values, matching HTTP query-string semantics.
	// Ignored for non-GET methods; use Parameters for write bodies.
	GetParameters map[string][]string `json:"getParameters,omitempty"`
	// Result type defines which data is returned from the generator.
	// By default, it is the "data" section of the Vault API response.
	// When using e.g. /auth/token/create the "data" section is empty but
	// the "auth" section contains the generated token.
	// Please refer to the vault docs regarding the result data structure.
	// Additionally, accessing the raw response is possibly by using "Raw" result type.
	ResultType *generatorsv1alpha1.VaultDynamicSecretResultType `json:"resultType,omitempty"`
	// Used to configure http retries if failed
	RetrySettings *externalsecretsv1.SecretStoreRetrySettings `json:"retrySettings,omitempty"`
	// Vault provider common spec
	Provider *externalsecretsv1.VaultProvider `json:"provider,omitempty"`
	// Vault path to obtain the dynamic secret from
	Path *string `json:"path,omitempty"`
	// Do not fail if no secrets are found. Useful for requests where no data is expected.
	AllowEmptyResponse *bool `json:"allowEmptyResponse,omitempty"`
}

// VaultDynamicSecretSpecApplyConfiguration constructs a declarative configuration of the VaultDynamicSecretSpec type for use with
// apply.
func VaultDynamicSecretSpec() *VaultDynamicSecretSpecApplyConfiguration {
	return &VaultDynamicSecretSpecApplyConfiguration{}
}

// WithController sets the Controller field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Controller field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithController(value string) *VaultDynamicSecretSpecApplyConfiguration {
	b.Controller = &value
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithMethod(value string) *VaultDynamicSecretSpecApplyConfiguration {
	b.Method = &value
	return b
}

// WithParameters sets the Parameters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Parameters field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithParameters(value v1.JSON) *VaultDynamicSecretSpecApplyConfiguration {
	b.Parameters = &value
	return b
}

// WithGetParameters puts the entries into the GetParameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the GetParameters field,
// overwriting an existing map entries in GetParameters field with the same key.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithGetParameters(entries map[string][]string) *VaultDynamicSecretSpecApplyConfiguration {
	if b.GetParameters == nil && len(entries) > 0 {
		b.GetParameters = make(map[string][]string, len(entries))
	}
	for k, v := range entries {
		b.GetParameters[k] = v
	}
	return b
}

// WithResultType sets the ResultType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResultType field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithResultType(value generatorsv1alpha1.VaultDynamicSecretResultType) *VaultDynamicSecretSpecApplyConfiguration {
	b.ResultType = &value
	return b
}

// WithRetrySettings sets the RetrySettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetrySettings field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithRetrySettings(value externalsecretsv1.SecretStoreRetrySettings) *VaultDynamicSecretSpecApplyConfiguration {
	b.RetrySettings = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithProvider(value externalsecretsv1.VaultProvider) *VaultDynamicSecretSpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithPath(value string) *VaultDynamicSecretSpecApplyConfiguration {
	b.Path = &value
	return b
}

// WithAllowEmptyResponse sets the AllowEmptyResponse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowEmptyResponse field is set to the value of the last call.
func (b *VaultDynamicSecretSpecApplyConfiguration) WithAllowEmptyResponse(value bool) *VaultDynamicSecretSpecApplyConfiguration {
	b.AllowEmptyResponse = &value
	return b
}
