/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WebhookSpecApplyConfiguration represents a declarative configuration of the WebhookSpec type for use
// with apply.
//
// WebhookSpec controls the behavior of the external generator. Any body parameters should be passed to the server through the parameters field.
type WebhookSpecApplyConfiguration struct {
	// Webhook Method
	Method *string `json:"method,omitempty"`
	// Webhook url to call
	URL *string `json:"url,omitempty"`
	// Headers
	Headers map[string]string `json:"headers,omitempty"`
	// Auth specifies a authorization protocol. Only one protocol may be set.
	Auth *AuthorizationProtocolApplyConfiguration `json:"auth,omitempty"`
	// Body
	Body *string `json:"body,omitempty"`
	// Timeout
	Timeout *v1.Duration `json:"timeout,omitempty"`
	// Result formatting
	Result *WebhookResultApplyConfiguration `json:"result,omitempty"`
	// Secrets to fill in templates
	// These secrets will be passed to the templating function as key value pairs under the given name
	Secrets []WebhookSecretApplyConfiguration `json:"secrets,omitempty"`
	// PEM encoded CA bundle used to validate webhook server certificate. Only used
	// if the Server URL is using HTTPS protocol. This parameter is ignored for
	// plain HTTP protocol connection. If not set the system root certificates
	// are used to validate the TLS connection.
	CABundle []byte `json:"caBundle,omitempty"`
	// The provider for the CA bundle to use to validate webhook server certificate.
	CAProvider *WebhookCAProviderApplyConfiguration `json:"caProvider,omitempty"`
}

// WebhookSpecApplyConfiguration constructs a declarative configuration of the WebhookSpec type for use with
// apply.
func WebhookSpec() *WebhookSpecApplyConfiguration {
	return &WebhookSpecApplyConfiguration{}
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *WebhookSpecApplyConfiguration) WithMethod(value string) *WebhookSpecApplyConfiguration {
	b.Method = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *WebhookSpecApplyConfiguration) WithURL(value string) *WebhookSpecApplyConfiguration {
	b.URL = &value
	return b
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *WebhookSpecApplyConfiguration) WithHeaders(entries map[string]string) *WebhookSpecApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *WebhookSpecApplyConfiguration) WithAuth(value *AuthorizationProtocolApplyConfiguration) *WebhookSpecApplyConfiguration {
	b.Auth = value
	return b
}

// WithBody sets the Body field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Body field is set to the value of the last call.
func (b *WebhookSpecApplyConfiguration) WithBody(value string) *WebhookSpecApplyConfiguration {
	b.Body = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *WebhookSpecApplyConfiguration) WithTimeout(value v1.Duration) *WebhookSpecApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithResult sets the Result field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Result field is set to the value of the last call.
func (b *WebhookSpecApplyConfiguration) WithResult(value *WebhookResultApplyConfiguration) *WebhookSpecApplyConfiguration {
	b.Result = value
	return b
}

// WithSecrets adds the given value to the Secrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Secrets field.
func (b *WebhookSpecApplyConfiguration) WithSecrets(values ...*WebhookSecretApplyConfiguration) *WebhookSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSecrets")
		}
		b.Secrets = append(b.Secrets, *values[i])
	}
	return b
}

// WithCABundle adds the given value to the CABundle field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CABundle field.
func (b *WebhookSpecApplyConfiguration) WithCABundle(values ...byte) *WebhookSpecApplyConfiguration {
	for i := range values {
		b.CABundle = append(b.CABundle, values[i])
	}
	return b
}

// WithCAProvider sets the CAProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAProvider field is set to the value of the last call.
func (b *WebhookSpecApplyConfiguration) WithCAProvider(value *WebhookCAProviderApplyConfiguration) *WebhookSpecApplyConfiguration {
	b.CAProvider = value
	return b
}
