---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fetch-from-onepassword
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: test-login-1
      remoteRef:
        key: test-login-1/username
  # OR
  dataFrom:
    - extract:
        key: test-login-1
        property: username # optional field Label to match exactly
    # OR
    - find:
        path: my-env-config # optional Item Title to match exactly
        name:
          regexp: "^username$"
    # OR
    - find:
        tags:
          tag1: "" # optional tags to match - value is unused, just needs to be present
