apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store # Must match SecretStore on the cluster

  target:
    name: database-credentials-json # Name for the secret to be created on the cluster
    creationPolicy: Owner

  # Extract only the "db" object from a JSON secret and create one Kubernetes
  # secret key per field inside it (e.g. username, password).
  dataFrom:
  - extract:
      key: database-credentials # Full path of the secret on Akeyless
      property: db
