apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-certificate-manager
spec:
  provider:
    aws:
      service: CertificateManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
