apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acm-exported-cert-chain
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: aws-certificate-manager
  target:
    template:
      type: kubernetes.io/tls
      engineVersion: v2
      data:
        ca.crt: '{{ .cert | filterPEM "CERTIFICATE" | filterCertChain "intermediate" }}'
        tls.crt: '{{ .cert | filterPEM "CERTIFICATE" | filterCertChain "leaf" }}'
        tls.key: '{{ .cert | filterPEM "PRIVATE KEY" }}'
  data:
    - secretKey: cert
      remoteRef:
        key: arn:aws:acm:us-east-1:123456789012:certificate/abcd-1234
