apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: beyondtrustsecrets-ss
  namespace: external-secrets
spec:
  provider:
    beyondtrustsecrets:
      auth:
        apikey:
          token:
            name: bts-api-token
            key: token
      server:
        apiUrl: "https://api.beyondtrust.io/site"
        siteId: "d6878b18-039a-4011-a1e4-a4523dbd4837"
      folderPath: "eso/static"
