apiVersion: generators.external-secrets.io/v1alpha1
kind: BeyondtrustSecretsDynamicSecret
metadata:
  name: aws-dynamic-generator
  namespace: external-secrets
spec:
  provider:
    auth:
      apikey:
        token:
          name: bts-api-token
          key: token
    server:
      apiUrl: "https://api.beyondtrust.io/site"
      siteId: <SITE_ID>
    folderPath: <FOLDER_PATH>
