apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-aws-credentials
  namespace: external-secrets
spec:
  refreshInterval: 5m
  refreshPolicy: Periodic
  target:
    name: app-aws-credentials
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: BeyondtrustWorkloadCredentialsDynamicSecret
          name: aws-dynamic-generator
