apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beyondtrustsecret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  refreshPolicy: Periodic
  secretStoreRef:
    name: beyondtrustworkloadcredentials-ss
    kind: SecretStore
  target:
    name: my-beyondtrust-secret
  dataFrom:
    - find:
        name:
          regexp: ".*"
