apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: conjur
spec:
  provider:
    conjur:
      # Service URL
      url: https://myapi.conjur.org
      # [OPTIONAL] base64 encoded string of certificate
      caBundle: OPTIONALxFIELDxxxBase64xCertxString==
      auth:
        cert:
          # conjur account
          account: conjur
          # The authn-cert service ID
          serviceID: my-cert-auth-service
          # [OPTIONAL] HostID for cert authentication (leave empty for 'spiffe' mode).
          # hostId: vm-01
          # Reference to a Kubernetes secret containing the PEM-encoded client certificate
          clientCertRef:
            name: conjur-client-cert
            key: tls.crt
          # Reference to a Kubernetes secret containing the PEM-encoded client key
          clientKeyRef:
            name: conjur-client-cert
            key: tls.key

