apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: app-config
  dataFrom:
  - extract:
      key: config/myapp
    select:
    - regexp: "^_"
      operation: Exclude
