apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-token
spec:
  refreshInterval: "30m0s"
  target:
    name: grafana-token
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Grafana
        name: grafana-token
