apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: garage-access-key
spec:
  # 12 random characters, hex encoded to 24 characters
  length: 12
  encoding: hex
  prefix: GK
