apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appIDRef: # (1) reference to a secret containing the GitHub App ID
    name: github-configuration-secret
    key: githubAppID
  installIDRef: # (2) reference to a secret containing the GitHub App installation ID
    name: github-configuration-secret
    key: githubAppInstallID
  auth:
    privateKey:
      secretRef:
        name: github-configuration-secret
        key: githubAppPrivateKey
