apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "sts-assumerole-secret"
spec:
  refreshInterval: "1h0m0s"
  target:
    name: sts-assumerole-secret
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: STSAssumeRoleToken
        name: "sts-assumerole-gen"
