apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gitea-push-secret
spec:
  deletionPolicy: Delete
  refreshInterval: 10m
  secretStoreRefs:
    - name: gitea-secret-store
      kind: SecretStore
  selector:
    secret:
      name: my-kubernetes-secret
  data:
    - match:
        secretKey: myKey
        remoteRef:
          remoteKey: MY_VARIABLE  # Target Gitea Actions Secret name
