apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gitea-secret-store
  target:
    name: my-secret
    creationPolicy: Owner
  data:
    - secretKey: myKey
      remoteRef:
        key: MY_VARIABLE  # Name of the Gitea Actions Variable
