apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical

  target:
    name: auth-api

  dataFrom:
    - find:
        # Filter by secret name using a regular expression.
        name:
          regexp: "^DB_.*"
        # Optionally also restrict to a folder path (must be an absolute path
        # starting with `/`). Omit to search the entire secretsScope.secretsPath.
        # path: /my-app
