apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: example
spec:
  provider:
    openbao:
      server: "https://openbao.acme.org"
      path: "secret"
      version: "v2"
      auth:
        # points to a secret that contains an OpenBao token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "my-secret"
          key: "vault-token"
