apiVersion: v1
kind: Secret
metadata:
  name: openbao-tls-cert
  namespace: external-secrets
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    <your-client-certificate>
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    <your-client-private-key>
    -----END PRIVATE KEY-----
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-cert-auth
spec:
  provider:
    openbao:
      server: "https://openbao.example.com"
      path: "secret"
      version: "v2"
      caProvider:
        type: "ConfigMap"
        namespace: "external-secrets"
        name: "openbao-ca-bundle"
        key: "ca.crt"
      auth:
        cert:
          clientCert:
            name: openbao-tls-cert
            namespace: "external-secrets"
            key: tls.crt
          secretRef:
            name: openbao-tls-cert
            namespace: "external-secrets"
            key: tls.key
