apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: passbolt-folder-example
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: passbolt
    kind: SecretStore
  target:
    name: passbolt-folder-example
  dataFrom:
    - find:
        # Replace with the ID of an existing Passbolt folder
        path: fdc478e2-f09b-47a6-9764-2e5d13f7fd0c
