---
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
stringData:
  source-key: "my-secret-value"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: proton-pass-push-example
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: proton-pass
      kind: SecretStore
  selector:
    secret:
      name: source-secret # source Kubernetes Secret
  data:
    - match:
        secretKey: source-key # key within the source Secret to push
        remoteRef:
          remoteKey: my-app-credentials # Proton Pass item title
          property: password            # field label, defaults to "password"
