apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonpass-find
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: protonpass
    kind: SecretStore
  target:
    name: all-db-secrets
    creationPolicy: Owner
  dataFrom:
    # Find all items matching the pattern
    - find:
        name:
          regexp: "Database.*"
