apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonpass-datafrom
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: protonpass
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  dataFrom:
    # Fetch all fields from the item as key-value pairs
    - extract:
        key: "Database Credentials"
