apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: proton-pass-store
  namespace: default
spec:
  provider:
    protonpass:
      auth:
        personalAccessTokenSecretRef:
          name: proton-pass-token
          key: pat
