apiVersion: external-secrets.io/v1
kind: PushSecret
metadata:
  name: safeguard-push-password
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: safeguard-store
      kind: SecretStore
  selector:
    secret:
      name: source-secret
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: accountName/assetName
          property: password
