apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: safeguard-store
spec:
  provider:
    safeguard:
      appliance: https://safeguard-api-host-name
      apiVersion: v3
      auth:
        a2a:
          certificate:
            secretRef:
              name: safeguard-a2a-cert
              key: tls.crt
          certificateKey:
            secretRef:
              name: safeguard-a2a-cert
              key: tls.key
      caProvider:
        type: Secret
        name: safeguard-ca
        key: ca.crt
