apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: safeguard-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: safeguard-store
    kind: SecretStore
  target:
    name: safeguard-password
  data:
    - secretKey: password
      remoteRef:
        key: accountName/assetName
        property: password
