apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sap-credential-store-example
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: sap-credential-store
  target:
    name: my-sap-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: my-password-credential
    - secretKey: api-key
      remoteRef:
        key: my-key-credential
        property: key
