apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: sap-credential-store
spec:
  provider:
    sapCredentialStore:
      serviceURL: https://credstore.cfapps.eu10.hana.ondemand.com
      namespace: my-namespace
      auth:
        mtls:
          certificate:
            secretRef:
              name: sap-credstore-mtls
              namespace: external-secrets
              key: certificate
          privateKey:
            secretRef:
              name: sap-credstore-mtls
              namespace: external-secrets
              key: private-key
