apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: acm-certificate
spec:
  deletionPolicy: Delete
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: aws-certificate-manager
      kind: SecretStore
  selector:
    secret:
      name: my-tls-cert
  data:
    - match:
        remoteRef:
          remoteKey: my-app-certificate
