apiVersion: v1
kind: Secret
metadata:
  name: passbolt-custom-fields
data:
  api_token: my-api-token-value
  deploy_key: ssh-ed25519-AAAA...
  full_secret: '{"name":"my-service","username":"deploy","password":"supersecretpassword","uri":"https://example.com","description":"","custom_fields":{"api-token":"my-api-token-value","deploy-key":"ssh-ed25519-AAAA..."}}'
type: Opaque
