// /*
// Copyright © 2025 ESO Maintainer Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	esmeta "github.com/external-secrets/external-secrets/apis/meta/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MongoDBSpec controls the behavior of the MongoDB generator.
type MongoDBSpec struct {
	Database MongoDBDatabase `json:"database"`
	// Auth is the authentication configuration to authenticate
	// against the MongoDB instance.
	Auth MongoDBAuth `json:"auth"`
	// User is the configuration for the service account that
	// is supposed to be generated by the generator.
	User MongoDBUser `json:"user"`
}

// MongoDBDatabase defines the MongoDB database configuration.
type MongoDBDatabase struct {
	// AdminDB is the name of the admin database
	// +kubebuilder:default="admin"
	// +optional
	AdminDB string `json:"adminDB"`
	Host    string `json:"host"`
	// Port is the port of the MongoDB instance. Defaults to 27017
	// +optional
	// +kubebuilder:default=27017
	Port int `json:"port"`
}

// MongoDBRole defines a MongoDB role configuration.
type MongoDBRole struct {
	// Name is the name of the role linked to the service account.
	Name string `json:"name"`
	// DB is where the role will be applied.
	DB string `json:"db"`
}

// MongoDBUser defines a MongoDB user configuration.
type MongoDBUser struct {
	// Name is the name of the service account.
	// If not provided, the generator will create one.
	// +optional
	Name string `json:"name"`
	// Roles is the configuration for the service account
	Roles []MongoDBRole `json:"roles"`
}

// MongoDBAuth defines MongoDB authentication configuration.
type MongoDBAuth struct {
	// Basic auth credentials used to authenticate against the MongoDB instance.
	// Note: you need a token which has elevated permissions to create service accounts.
	// +optional
	SCRAM *MongoDBSCRAMAuth `json:"scram,omitempty"`
}

// MongoDBSCRAMAuth defines SCRAM authentication for MongoDB.
type MongoDBSCRAMAuth struct {
	Username  *string               `json:"username,omitempty"`
	SecretRef *MongoDBAuthSecretRef `json:"secretRef,omitempty"`
}

// MongoDBAuthSecretRef defines secret references for MongoDB authentication.
type MongoDBAuthSecretRef struct {
	Password esmeta.SecretKeySelector  `json:"passwordSecretRef,omitempty"`
	Username *esmeta.SecretKeySelector `json:"usernameSecretRef,omitempty"`
}

// MongoDB represents a MongoDB generator configuration.
// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:metadata:labels="external-secrets.io/component=controller"
// +kubebuilder:resource:scope=Namespaced,categories={external-secrets, external-secrets-generators}
type MongoDB struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MongoDBSpec     `json:"spec,omitempty"`
	Status GeneratorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MongoDBList contains a list of MongoDB Generator resources.
type MongoDBList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MongoDB `json:"items"`
}

// MongoDBUserState represents the state of a MongoDB user.
type MongoDBUserState struct {
	User string `json:"user"`
}
