#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROVIDERS_DIR="${PROJECT_ROOT}/providers/v1"
OUTPUT_FILE="${PROJECT_ROOT}/pkg/providers/imports/generated_imports.go"

# Ensure output directory exists
mkdir -p "$(dirname "${OUTPUT_FILE}")"

# Discover all providers (directories with provider.go)
PROVIDERS=()
for provider_dir in "${PROVIDERS_DIR}"/*; do
    if [[ -d "${provider_dir}" && -f "${provider_dir}/provider.go" ]]; then
        provider_name=$(basename "${provider_dir}")
        PROVIDERS+=("${provider_name}")
    fi
done

# Sort providers for deterministic output
IFS=$'\n' PROVIDERS=($(sort <<<"${PROVIDERS[*]}"))
unset IFS

# Generate header
cat > "${OUTPUT_FILE}" << 'EOF'
// Code generated by hack/generate-provider-imports.sh. DO NOT EDIT.

/*
Copyright © 2025 ESO Maintainer Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package imports provides automatic importing of all provider packages
// for registration via their init() functions.
package imports

import (
EOF

# Generate imports for each provider
for provider in "${PROVIDERS[@]}"; do
    echo "	_ \"github.com/external-secrets/external-secrets/providers/v1/${provider}\" // ${provider} provider registration" >> "${OUTPUT_FILE}"
done

# Close the import block
echo ")" >> "${OUTPUT_FILE}"

echo "Generated provider imports for ${#PROVIDERS[@]} providers: ${PROVIDERS[*]}"
