apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: default
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: aws-secretsmanager
      kind: SecretStore
  selector:
    secret:
      name: pokedex-credentials
  data:
    - match:
        secretKey: my-secret-key
        remoteRef:
          remoteKey: my-remote-secret
          property: password
      metadata:
        kmsKeyID: bb123123-b2b0-4f60-ac3a-44a13f0e6b6c
        replicationLocations:
          - eu-north-1
          - eu-west-2
        secretPushFormat: string
        description: "Cross-account accessible secret"
        tags:
          team: platform-engineering
