apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: multiple-passwords
spec:
  length: 36
  secretKeys:
    - key1
    - key2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secrets
spec:
  refreshInterval: "30m"
  target:
    name: auth-secrets
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: multiple-passwords
