/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/external-secrets/external-secrets/apis/generators/v1alpha1"
	scheme "github.com/external-secrets/external-secrets/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PasswordsGetter has a method to return a PasswordInterface.
// A group's client should implement this interface.
type PasswordsGetter interface {
	Passwords(namespace string) PasswordInterface
}

// PasswordInterface has methods to work with Password resources.
type PasswordInterface interface {
	Create(ctx context.Context, password *v1alpha1.Password, opts v1.CreateOptions) (*v1alpha1.Password, error)
	Update(ctx context.Context, password *v1alpha1.Password, opts v1.UpdateOptions) (*v1alpha1.Password, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Password, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PasswordList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Password, err error)
	PasswordExpansion
}

// passwords implements PasswordInterface
type passwords struct {
	*gentype.ClientWithList[*v1alpha1.Password, *v1alpha1.PasswordList]
}

// newPasswords returns a Passwords
func newPasswords(c *GeneratorsV1alpha1Client, namespace string) *passwords {
	return &passwords{
		gentype.NewClientWithList[*v1alpha1.Password, *v1alpha1.PasswordList](
			"passwords",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.Password { return &v1alpha1.Password{} },
			func() *v1alpha1.PasswordList { return &v1alpha1.PasswordList{} }),
	}
}
