apiVersion: v1
kind: Secret
metadata:
  name: source-certificate
data:
  cert.p12: <BASE64_ENCODED_P12_CERTIFICATE>
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: default
spec:
  refreshInterval: 1h0m0s # Refresh interval for which push secret will reconcile
  deletionPolicy: Delete
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: azure-store
      kind: SecretStore
  selector:
    secret:
      name: source-certificate # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: cert.p12 # Source Kubernetes secret key containing the P12 certificate
        remoteRef:
          remoteKey: cert/my-azkv-cert-name
