/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// AkeylessAuthSecretRefApplyConfiguration represents a declarative configuration of the AkeylessAuthSecretRef type for use
// with apply.
//
// AkeylessAuthSecretRef references a Secret that contains the details
// to authenticate with Akeyless.
// AKEYLESS_ACCESS_TYPE_PARAM: AZURE_OBJ_ID OR GCP_AUDIENCE OR ACCESS_KEY OR KUB_CONFIG_NAME.
type AkeylessAuthSecretRefApplyConfiguration struct {
	// The SecretAccessID is used for authentication
	AccessID        *metav1.SecretKeySelector `json:"accessID,omitempty"`
	AccessType      *metav1.SecretKeySelector `json:"accessType,omitempty"`
	AccessTypeParam *metav1.SecretKeySelector `json:"accessTypeParam,omitempty"`
}

// AkeylessAuthSecretRefApplyConfiguration constructs a declarative configuration of the AkeylessAuthSecretRef type for use with
// apply.
func AkeylessAuthSecretRef() *AkeylessAuthSecretRefApplyConfiguration {
	return &AkeylessAuthSecretRefApplyConfiguration{}
}

// WithAccessID sets the AccessID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessID field is set to the value of the last call.
func (b *AkeylessAuthSecretRefApplyConfiguration) WithAccessID(value metav1.SecretKeySelector) *AkeylessAuthSecretRefApplyConfiguration {
	b.AccessID = &value
	return b
}

// WithAccessType sets the AccessType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessType field is set to the value of the last call.
func (b *AkeylessAuthSecretRefApplyConfiguration) WithAccessType(value metav1.SecretKeySelector) *AkeylessAuthSecretRefApplyConfiguration {
	b.AccessType = &value
	return b
}

// WithAccessTypeParam sets the AccessTypeParam field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessTypeParam field is set to the value of the last call.
func (b *AkeylessAuthSecretRefApplyConfiguration) WithAccessTypeParam(value metav1.SecretKeySelector) *AkeylessAuthSecretRefApplyConfiguration {
	b.AccessTypeParam = &value
	return b
}
