/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	externalsecretsv1 "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
)

// AWSProviderApplyConfiguration represents a declarative configuration of the AWSProvider type for use
// with apply.
//
// AWSProvider configures a store to sync secrets with AWS.
type AWSProviderApplyConfiguration struct {
	// Service defines which service should be used to fetch the secrets
	Service *externalsecretsv1.AWSServiceType `json:"service,omitempty"`
	// Auth defines the information necessary to authenticate against AWS
	// if not set aws sdk will infer credentials from your environment
	// see: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials
	Auth *AWSAuthApplyConfiguration `json:"auth,omitempty"`
	// Role is a Role ARN which the provider will assume
	Role *string `json:"role,omitempty"`
	// AWS Region to be used for the provider
	Region *string `json:"region,omitempty"`
	// AdditionalRoles is a chained list of Role ARNs which the provider will sequentially assume before assuming the Role
	AdditionalRoles []string `json:"additionalRoles,omitempty"`
	// AWS External ID set on assumed IAM roles
	ExternalID *string `json:"externalID,omitempty"`
	// AWS STS assume role session tags
	SessionTags []*externalsecretsv1.Tag `json:"sessionTags,omitempty"`
	// SecretsManager defines how the provider behaves when interacting with AWS SecretsManager
	SecretsManager *SecretsManagerApplyConfiguration `json:"secretsManager,omitempty"`
	// AWS STS assume role transitive session tags. Required when multiple rules are used with the provider
	TransitiveTagKeys []string `json:"transitiveTagKeys,omitempty"`
	// SessionTagsPolicy controls whether and how STS session tags are added when assuming roles.
	// None (default): no tags are added.
	// Simple: automatically adds esoNamespace (from the ExternalSecret), esoStoreName, and esoStoreKind tags.
	// Custom: adds esoNamespace, esoStoreName, and esoStoreKind plus any tags defined in CustomSessionTags.
	// Note: the IAM role must have sts:TagSession permission when using Simple or Custom.
	SessionTagsPolicy *externalsecretsv1.SessionTagsPolicy `json:"sessionTagsPolicy,omitempty"`
	// CustomSessionTags defines additional STS session tags to include when SessionTagsPolicy is Custom.
	// These are merged with the automatically injected esoNamespace, esoStoreName, and esoStoreKind tags.
	CustomSessionTags map[string]string `json:"customSessionTags,omitempty"`
	// Prefix adds a prefix to all retrieved values.
	Prefix *string `json:"prefix,omitempty"`
}

// AWSProviderApplyConfiguration constructs a declarative configuration of the AWSProvider type for use with
// apply.
func AWSProvider() *AWSProviderApplyConfiguration {
	return &AWSProviderApplyConfiguration{}
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithService(value externalsecretsv1.AWSServiceType) *AWSProviderApplyConfiguration {
	b.Service = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithAuth(value *AWSAuthApplyConfiguration) *AWSProviderApplyConfiguration {
	b.Auth = value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithRole(value string) *AWSProviderApplyConfiguration {
	b.Role = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithRegion(value string) *AWSProviderApplyConfiguration {
	b.Region = &value
	return b
}

// WithAdditionalRoles adds the given value to the AdditionalRoles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalRoles field.
func (b *AWSProviderApplyConfiguration) WithAdditionalRoles(values ...string) *AWSProviderApplyConfiguration {
	for i := range values {
		b.AdditionalRoles = append(b.AdditionalRoles, values[i])
	}
	return b
}

// WithExternalID sets the ExternalID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalID field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithExternalID(value string) *AWSProviderApplyConfiguration {
	b.ExternalID = &value
	return b
}

// WithSessionTags adds the given value to the SessionTags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SessionTags field.
func (b *AWSProviderApplyConfiguration) WithSessionTags(values ...**externalsecretsv1.Tag) *AWSProviderApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSessionTags")
		}
		b.SessionTags = append(b.SessionTags, *values[i])
	}
	return b
}

// WithSecretsManager sets the SecretsManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretsManager field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithSecretsManager(value *SecretsManagerApplyConfiguration) *AWSProviderApplyConfiguration {
	b.SecretsManager = value
	return b
}

// WithTransitiveTagKeys adds the given value to the TransitiveTagKeys field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TransitiveTagKeys field.
func (b *AWSProviderApplyConfiguration) WithTransitiveTagKeys(values ...string) *AWSProviderApplyConfiguration {
	for i := range values {
		b.TransitiveTagKeys = append(b.TransitiveTagKeys, values[i])
	}
	return b
}

// WithSessionTagsPolicy sets the SessionTagsPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionTagsPolicy field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithSessionTagsPolicy(value externalsecretsv1.SessionTagsPolicy) *AWSProviderApplyConfiguration {
	b.SessionTagsPolicy = &value
	return b
}

// WithCustomSessionTags puts the entries into the CustomSessionTags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the CustomSessionTags field,
// overwriting an existing map entries in CustomSessionTags field with the same key.
func (b *AWSProviderApplyConfiguration) WithCustomSessionTags(entries map[string]string) *AWSProviderApplyConfiguration {
	if b.CustomSessionTags == nil && len(entries) > 0 {
		b.CustomSessionTags = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CustomSessionTags[k] = v
	}
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *AWSProviderApplyConfiguration) WithPrefix(value string) *AWSProviderApplyConfiguration {
	b.Prefix = &value
	return b
}
