/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// BarbicanProviderApplyConfiguration represents a declarative configuration of the BarbicanProvider type for use
// with apply.
//
// BarbicanProvider setup a store to sync secrets with barbican.
type BarbicanProviderApplyConfiguration struct {
	AuthURL    *string                         `json:"authURL,omitempty"`
	TenantName *string                         `json:"tenantName,omitempty"`
	DomainName *string                         `json:"domainName,omitempty"`
	Region     *string                         `json:"region,omitempty"`
	Auth       *BarbicanAuthApplyConfiguration `json:"auth,omitempty"`
}

// BarbicanProviderApplyConfiguration constructs a declarative configuration of the BarbicanProvider type for use with
// apply.
func BarbicanProvider() *BarbicanProviderApplyConfiguration {
	return &BarbicanProviderApplyConfiguration{}
}

// WithAuthURL sets the AuthURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthURL field is set to the value of the last call.
func (b *BarbicanProviderApplyConfiguration) WithAuthURL(value string) *BarbicanProviderApplyConfiguration {
	b.AuthURL = &value
	return b
}

// WithTenantName sets the TenantName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenantName field is set to the value of the last call.
func (b *BarbicanProviderApplyConfiguration) WithTenantName(value string) *BarbicanProviderApplyConfiguration {
	b.TenantName = &value
	return b
}

// WithDomainName sets the DomainName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainName field is set to the value of the last call.
func (b *BarbicanProviderApplyConfiguration) WithDomainName(value string) *BarbicanProviderApplyConfiguration {
	b.DomainName = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BarbicanProviderApplyConfiguration) WithRegion(value string) *BarbicanProviderApplyConfiguration {
	b.Region = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *BarbicanProviderApplyConfiguration) WithAuth(value *BarbicanAuthApplyConfiguration) *BarbicanProviderApplyConfiguration {
	b.Auth = value
	return b
}
