/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// BeyondtrustAuthApplyConfiguration represents a declarative configuration of the BeyondtrustAuth type for use
// with apply.
//
// BeyondtrustAuth provides different ways to authenticate to a BeyondtrustProvider server.
type BeyondtrustAuthApplyConfiguration struct {
	// APIKey If not provided then ClientID/ClientSecret become required.
	APIKey *BeyondTrustProviderSecretRefApplyConfiguration `json:"apiKey,omitempty"`
	// ClientID is the API OAuth Client ID.
	ClientID *BeyondTrustProviderSecretRefApplyConfiguration `json:"clientId,omitempty"`
	// ClientSecret is the API OAuth Client Secret.
	ClientSecret *BeyondTrustProviderSecretRefApplyConfiguration `json:"clientSecret,omitempty"`
	// Certificate (cert.pem) for use when authenticating with an OAuth client Id using a Client Certificate.
	Certificate *BeyondTrustProviderSecretRefApplyConfiguration `json:"certificate,omitempty"`
	// Certificate private key (key.pem). For use when authenticating with an OAuth client Id
	CertificateKey *BeyondTrustProviderSecretRefApplyConfiguration `json:"certificateKey,omitempty"`
}

// BeyondtrustAuthApplyConfiguration constructs a declarative configuration of the BeyondtrustAuth type for use with
// apply.
func BeyondtrustAuth() *BeyondtrustAuthApplyConfiguration {
	return &BeyondtrustAuthApplyConfiguration{}
}

// WithAPIKey sets the APIKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIKey field is set to the value of the last call.
func (b *BeyondtrustAuthApplyConfiguration) WithAPIKey(value *BeyondTrustProviderSecretRefApplyConfiguration) *BeyondtrustAuthApplyConfiguration {
	b.APIKey = value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *BeyondtrustAuthApplyConfiguration) WithClientID(value *BeyondTrustProviderSecretRefApplyConfiguration) *BeyondtrustAuthApplyConfiguration {
	b.ClientID = value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *BeyondtrustAuthApplyConfiguration) WithClientSecret(value *BeyondTrustProviderSecretRefApplyConfiguration) *BeyondtrustAuthApplyConfiguration {
	b.ClientSecret = value
	return b
}

// WithCertificate sets the Certificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certificate field is set to the value of the last call.
func (b *BeyondtrustAuthApplyConfiguration) WithCertificate(value *BeyondTrustProviderSecretRefApplyConfiguration) *BeyondtrustAuthApplyConfiguration {
	b.Certificate = value
	return b
}

// WithCertificateKey sets the CertificateKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateKey field is set to the value of the last call.
func (b *BeyondtrustAuthApplyConfiguration) WithCertificateKey(value *BeyondTrustProviderSecretRefApplyConfiguration) *BeyondtrustAuthApplyConfiguration {
	b.CertificateKey = value
	return b
}
