/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// CertAuthApplyConfiguration represents a declarative configuration of the CertAuth type for use
// with apply.
//
// CertAuth defines certificate-based authentication configuration for Kubernetes.
type CertAuthApplyConfiguration struct {
	ClientCert *metav1.SecretKeySelector `json:"clientCert,omitempty"`
	ClientKey  *metav1.SecretKeySelector `json:"clientKey,omitempty"`
}

// CertAuthApplyConfiguration constructs a declarative configuration of the CertAuth type for use with
// apply.
func CertAuth() *CertAuthApplyConfiguration {
	return &CertAuthApplyConfiguration{}
}

// WithClientCert sets the ClientCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCert field is set to the value of the last call.
func (b *CertAuthApplyConfiguration) WithClientCert(value metav1.SecretKeySelector) *CertAuthApplyConfiguration {
	b.ClientCert = &value
	return b
}

// WithClientKey sets the ClientKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientKey field is set to the value of the last call.
func (b *CertAuthApplyConfiguration) WithClientKey(value metav1.SecretKeySelector) *CertAuthApplyConfiguration {
	b.ClientKey = &value
	return b
}
