/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// ChefAuthApplyConfiguration represents a declarative configuration of the ChefAuth type for use
// with apply.
//
// ChefAuth contains a secretRef for credentials.
type ChefAuthApplyConfiguration struct {
	SecretRef *ChefAuthSecretRefApplyConfiguration `json:"secretRef,omitempty"`
}

// ChefAuthApplyConfiguration constructs a declarative configuration of the ChefAuth type for use with
// apply.
func ChefAuth() *ChefAuthApplyConfiguration {
	return &ChefAuthApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *ChefAuthApplyConfiguration) WithSecretRef(value *ChefAuthSecretRefApplyConfiguration) *ChefAuthApplyConfiguration {
	b.SecretRef = value
	return b
}
