/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// CSMAuthSecretRefApplyConfiguration represents a declarative configuration of the CSMAuthSecretRef type for use
// with apply.
//
// CSMAuthSecretRef holds secret references for Cloud.ru credentials.
type CSMAuthSecretRefApplyConfiguration struct {
	// The AccessKeyID is used for authentication
	AccessKeyID *metav1.SecretKeySelector `json:"accessKeyIDSecretRef,omitempty"`
	// The AccessKeySecret is used for authentication
	AccessKeySecret *metav1.SecretKeySelector `json:"accessKeySecretSecretRef,omitempty"`
}

// CSMAuthSecretRefApplyConfiguration constructs a declarative configuration of the CSMAuthSecretRef type for use with
// apply.
func CSMAuthSecretRef() *CSMAuthSecretRefApplyConfiguration {
	return &CSMAuthSecretRefApplyConfiguration{}
}

// WithAccessKeyID sets the AccessKeyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessKeyID field is set to the value of the last call.
func (b *CSMAuthSecretRefApplyConfiguration) WithAccessKeyID(value metav1.SecretKeySelector) *CSMAuthSecretRefApplyConfiguration {
	b.AccessKeyID = &value
	return b
}

// WithAccessKeySecret sets the AccessKeySecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessKeySecret field is set to the value of the last call.
func (b *CSMAuthSecretRefApplyConfiguration) WithAccessKeySecret(value metav1.SecretKeySelector) *CSMAuthSecretRefApplyConfiguration {
	b.AccessKeySecret = &value
	return b
}
