/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	externalsecretsv1 "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
)

// ExternalSecretRewriteMergeApplyConfiguration represents a declarative configuration of the ExternalSecretRewriteMerge type for use
// with apply.
//
// ExternalSecretRewriteMerge defines configuration for merging secret values.
type ExternalSecretRewriteMergeApplyConfiguration struct {
	// Used to define the target key of the merge operation.
	// Required if strategy is JSON. Ignored otherwise.
	Into *string `json:"into,omitempty"`
	// Used to define key priority in conflict resolution.
	Priority []string `json:"priority,omitempty"`
	// Used to define the policy when a key in the priority list does not exist in the input.
	PriorityPolicy *externalsecretsv1.ExternalSecretRewriteMergePriorityPolicy `json:"priorityPolicy,omitempty"`
	// Used to define the policy to use in conflict resolution.
	ConflictPolicy *externalsecretsv1.ExternalSecretRewriteMergeConflictPolicy `json:"conflictPolicy,omitempty"`
	// Used to define the strategy to use in the merge operation.
	Strategy *externalsecretsv1.ExternalSecretRewriteMergeStrategy `json:"strategy,omitempty"`
}

// ExternalSecretRewriteMergeApplyConfiguration constructs a declarative configuration of the ExternalSecretRewriteMerge type for use with
// apply.
func ExternalSecretRewriteMerge() *ExternalSecretRewriteMergeApplyConfiguration {
	return &ExternalSecretRewriteMergeApplyConfiguration{}
}

// WithInto sets the Into field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Into field is set to the value of the last call.
func (b *ExternalSecretRewriteMergeApplyConfiguration) WithInto(value string) *ExternalSecretRewriteMergeApplyConfiguration {
	b.Into = &value
	return b
}

// WithPriority adds the given value to the Priority field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Priority field.
func (b *ExternalSecretRewriteMergeApplyConfiguration) WithPriority(values ...string) *ExternalSecretRewriteMergeApplyConfiguration {
	for i := range values {
		b.Priority = append(b.Priority, values[i])
	}
	return b
}

// WithPriorityPolicy sets the PriorityPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityPolicy field is set to the value of the last call.
func (b *ExternalSecretRewriteMergeApplyConfiguration) WithPriorityPolicy(value externalsecretsv1.ExternalSecretRewriteMergePriorityPolicy) *ExternalSecretRewriteMergeApplyConfiguration {
	b.PriorityPolicy = &value
	return b
}

// WithConflictPolicy sets the ConflictPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConflictPolicy field is set to the value of the last call.
func (b *ExternalSecretRewriteMergeApplyConfiguration) WithConflictPolicy(value externalsecretsv1.ExternalSecretRewriteMergeConflictPolicy) *ExternalSecretRewriteMergeApplyConfiguration {
	b.ConflictPolicy = &value
	return b
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *ExternalSecretRewriteMergeApplyConfiguration) WithStrategy(value externalsecretsv1.ExternalSecretRewriteMergeStrategy) *ExternalSecretRewriteMergeApplyConfiguration {
	b.Strategy = &value
	return b
}
