/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExternalSecretStatusApplyConfiguration represents a declarative configuration of the ExternalSecretStatus type for use
// with apply.
//
// ExternalSecretStatus defines the observed state of ExternalSecret.
type ExternalSecretStatusApplyConfiguration struct {
	// refreshTime is the time and date the external secret was fetched and
	// the target secret updated
	RefreshTime *metav1.Time `json:"refreshTime,omitempty"`
	// SyncedResourceVersion keeps track of the last synced version
	SyncedResourceVersion *string                                           `json:"syncedResourceVersion,omitempty"`
	Conditions            []ExternalSecretStatusConditionApplyConfiguration `json:"conditions,omitempty"`
	// Binding represents a servicebinding.io Provisioned Service reference to the secret
	Binding *corev1.LocalObjectReference `json:"binding,omitempty"`
}

// ExternalSecretStatusApplyConfiguration constructs a declarative configuration of the ExternalSecretStatus type for use with
// apply.
func ExternalSecretStatus() *ExternalSecretStatusApplyConfiguration {
	return &ExternalSecretStatusApplyConfiguration{}
}

// WithRefreshTime sets the RefreshTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RefreshTime field is set to the value of the last call.
func (b *ExternalSecretStatusApplyConfiguration) WithRefreshTime(value metav1.Time) *ExternalSecretStatusApplyConfiguration {
	b.RefreshTime = &value
	return b
}

// WithSyncedResourceVersion sets the SyncedResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SyncedResourceVersion field is set to the value of the last call.
func (b *ExternalSecretStatusApplyConfiguration) WithSyncedResourceVersion(value string) *ExternalSecretStatusApplyConfiguration {
	b.SyncedResourceVersion = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ExternalSecretStatusApplyConfiguration) WithConditions(values ...*ExternalSecretStatusConditionApplyConfiguration) *ExternalSecretStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithBinding sets the Binding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Binding field is set to the value of the last call.
func (b *ExternalSecretStatusApplyConfiguration) WithBinding(value corev1.LocalObjectReference) *ExternalSecretStatusApplyConfiguration {
	b.Binding = &value
	return b
}
