/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	externalsecretsv1 "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
)

// FakeProviderApplyConfiguration represents a declarative configuration of the FakeProvider type for use
// with apply.
//
// FakeProvider configures a fake provider that returns static values.
type FakeProviderApplyConfiguration struct {
	Data             []FakeProviderDataApplyConfiguration `json:"data,omitempty"`
	ValidationResult *externalsecretsv1.ValidationResult  `json:"validationResult,omitempty"`
}

// FakeProviderApplyConfiguration constructs a declarative configuration of the FakeProvider type for use with
// apply.
func FakeProvider() *FakeProviderApplyConfiguration {
	return &FakeProviderApplyConfiguration{}
}

// WithData adds the given value to the Data field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Data field.
func (b *FakeProviderApplyConfiguration) WithData(values ...*FakeProviderDataApplyConfiguration) *FakeProviderApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithData")
		}
		b.Data = append(b.Data, *values[i])
	}
	return b
}

// WithValidationResult sets the ValidationResult field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValidationResult field is set to the value of the last call.
func (b *FakeProviderApplyConfiguration) WithValidationResult(value externalsecretsv1.ValidationResult) *FakeProviderApplyConfiguration {
	b.ValidationResult = &value
	return b
}
