/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// GCPWorkloadIdentityApplyConfiguration represents a declarative configuration of the GCPWorkloadIdentity type for use
// with apply.
//
// GCPWorkloadIdentity defines configuration for workload identity authentication to GCP.
type GCPWorkloadIdentityApplyConfiguration struct {
	ServiceAccountRef *metav1.ServiceAccountSelector `json:"serviceAccountRef,omitempty"`
	// ClusterLocation is the location of the cluster
	// If not specified, it fetches information from the metadata server
	ClusterLocation *string `json:"clusterLocation,omitempty"`
	// ClusterName is the name of the cluster
	// If not specified, it fetches information from the metadata server
	ClusterName *string `json:"clusterName,omitempty"`
	// ClusterProjectID is the project ID of the cluster
	// If not specified, it fetches information from the metadata server
	ClusterProjectID *string `json:"clusterProjectID,omitempty"`
}

// GCPWorkloadIdentityApplyConfiguration constructs a declarative configuration of the GCPWorkloadIdentity type for use with
// apply.
func GCPWorkloadIdentity() *GCPWorkloadIdentityApplyConfiguration {
	return &GCPWorkloadIdentityApplyConfiguration{}
}

// WithServiceAccountRef sets the ServiceAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountRef field is set to the value of the last call.
func (b *GCPWorkloadIdentityApplyConfiguration) WithServiceAccountRef(value metav1.ServiceAccountSelector) *GCPWorkloadIdentityApplyConfiguration {
	b.ServiceAccountRef = &value
	return b
}

// WithClusterLocation sets the ClusterLocation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterLocation field is set to the value of the last call.
func (b *GCPWorkloadIdentityApplyConfiguration) WithClusterLocation(value string) *GCPWorkloadIdentityApplyConfiguration {
	b.ClusterLocation = &value
	return b
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *GCPWorkloadIdentityApplyConfiguration) WithClusterName(value string) *GCPWorkloadIdentityApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithClusterProjectID sets the ClusterProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterProjectID field is set to the value of the last call.
func (b *GCPWorkloadIdentityApplyConfiguration) WithClusterProjectID(value string) *GCPWorkloadIdentityApplyConfiguration {
	b.ClusterProjectID = &value
	return b
}
