/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// GitlabSecretRefApplyConfiguration represents a declarative configuration of the GitlabSecretRef type for use
// with apply.
//
// GitlabSecretRef contains the secret reference for GitLab authentication credentials.
type GitlabSecretRefApplyConfiguration struct {
	// AccessToken is used for authentication.
	AccessToken *metav1.SecretKeySelector `json:"accessToken,omitempty"`
}

// GitlabSecretRefApplyConfiguration constructs a declarative configuration of the GitlabSecretRef type for use with
// apply.
func GitlabSecretRef() *GitlabSecretRefApplyConfiguration {
	return &GitlabSecretRefApplyConfiguration{}
}

// WithAccessToken sets the AccessToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessToken field is set to the value of the last call.
func (b *GitlabSecretRefApplyConfiguration) WithAccessToken(value metav1.SecretKeySelector) *GitlabSecretRefApplyConfiguration {
	b.AccessToken = &value
	return b
}
