/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// IBMAuthSecretRefApplyConfiguration represents a declarative configuration of the IBMAuthSecretRef type for use
// with apply.
//
// IBMAuthSecretRef contains the secret reference for IBM Cloud API key authentication.
type IBMAuthSecretRefApplyConfiguration struct {
	// The SecretAccessKey is used for authentication
	SecretAPIKey *metav1.SecretKeySelector `json:"secretApiKeySecretRef,omitempty"`
	// The IAM endpoint used to obain a token
	IAMEndpoint *string `json:"iamEndpoint,omitempty"`
}

// IBMAuthSecretRefApplyConfiguration constructs a declarative configuration of the IBMAuthSecretRef type for use with
// apply.
func IBMAuthSecretRef() *IBMAuthSecretRefApplyConfiguration {
	return &IBMAuthSecretRefApplyConfiguration{}
}

// WithSecretAPIKey sets the SecretAPIKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretAPIKey field is set to the value of the last call.
func (b *IBMAuthSecretRefApplyConfiguration) WithSecretAPIKey(value metav1.SecretKeySelector) *IBMAuthSecretRefApplyConfiguration {
	b.SecretAPIKey = &value
	return b
}

// WithIAMEndpoint sets the IAMEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IAMEndpoint field is set to the value of the last call.
func (b *IBMAuthSecretRefApplyConfiguration) WithIAMEndpoint(value string) *IBMAuthSecretRefApplyConfiguration {
	b.IAMEndpoint = &value
	return b
}
