/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// NgrokProviderApplyConfiguration represents a declarative configuration of the NgrokProvider type for use
// with apply.
//
// NgrokProvider configures a store to sync secrets with a ngrok vault to use in traffic policies.
// See: https://ngrok.com/blog-post/secrets-for-traffic-policy
type NgrokProviderApplyConfiguration struct {
	// APIURL is the URL of the ngrok API.
	APIURL *string `json:"apiUrl,omitempty"`
	// Auth configures how the ngrok provider authenticates with the ngrok API.
	Auth *NgrokAuthApplyConfiguration `json:"auth,omitempty"`
	// Vault configures the ngrok vault to sync secrets with.
	Vault *NgrokVaultApplyConfiguration `json:"vault,omitempty"`
}

// NgrokProviderApplyConfiguration constructs a declarative configuration of the NgrokProvider type for use with
// apply.
func NgrokProvider() *NgrokProviderApplyConfiguration {
	return &NgrokProviderApplyConfiguration{}
}

// WithAPIURL sets the APIURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIURL field is set to the value of the last call.
func (b *NgrokProviderApplyConfiguration) WithAPIURL(value string) *NgrokProviderApplyConfiguration {
	b.APIURL = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *NgrokProviderApplyConfiguration) WithAuth(value *NgrokAuthApplyConfiguration) *NgrokProviderApplyConfiguration {
	b.Auth = value
	return b
}

// WithVault sets the Vault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vault field is set to the value of the last call.
func (b *NgrokProviderApplyConfiguration) WithVault(value *NgrokVaultApplyConfiguration) *NgrokProviderApplyConfiguration {
	b.Vault = value
	return b
}
