/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// OciAuthCredentialsApplyConfiguration represents a declarative configuration of the OciAuthCredentials type for use
// with apply.
//
// OciAuthCredentials represents the credentials for OCI authentication.
type OciAuthCredentialsApplyConfiguration struct {
	IdentityID           *metav1.SecretKeySelector `json:"identityId,omitempty"`
	PrivateKey           *metav1.SecretKeySelector `json:"privateKey,omitempty"`
	PrivateKeyPassphrase *metav1.SecretKeySelector `json:"privateKeyPassphrase,omitempty"`
	Fingerprint          *metav1.SecretKeySelector `json:"fingerprint,omitempty"`
	UserID               *metav1.SecretKeySelector `json:"userId,omitempty"`
	TenancyID            *metav1.SecretKeySelector `json:"tenancyId,omitempty"`
	Region               *metav1.SecretKeySelector `json:"region,omitempty"`
}

// OciAuthCredentialsApplyConfiguration constructs a declarative configuration of the OciAuthCredentials type for use with
// apply.
func OciAuthCredentials() *OciAuthCredentialsApplyConfiguration {
	return &OciAuthCredentialsApplyConfiguration{}
}

// WithIdentityID sets the IdentityID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdentityID field is set to the value of the last call.
func (b *OciAuthCredentialsApplyConfiguration) WithIdentityID(value metav1.SecretKeySelector) *OciAuthCredentialsApplyConfiguration {
	b.IdentityID = &value
	return b
}

// WithPrivateKey sets the PrivateKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKey field is set to the value of the last call.
func (b *OciAuthCredentialsApplyConfiguration) WithPrivateKey(value metav1.SecretKeySelector) *OciAuthCredentialsApplyConfiguration {
	b.PrivateKey = &value
	return b
}

// WithPrivateKeyPassphrase sets the PrivateKeyPassphrase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateKeyPassphrase field is set to the value of the last call.
func (b *OciAuthCredentialsApplyConfiguration) WithPrivateKeyPassphrase(value metav1.SecretKeySelector) *OciAuthCredentialsApplyConfiguration {
	b.PrivateKeyPassphrase = &value
	return b
}

// WithFingerprint sets the Fingerprint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fingerprint field is set to the value of the last call.
func (b *OciAuthCredentialsApplyConfiguration) WithFingerprint(value metav1.SecretKeySelector) *OciAuthCredentialsApplyConfiguration {
	b.Fingerprint = &value
	return b
}

// WithUserID sets the UserID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserID field is set to the value of the last call.
func (b *OciAuthCredentialsApplyConfiguration) WithUserID(value metav1.SecretKeySelector) *OciAuthCredentialsApplyConfiguration {
	b.UserID = &value
	return b
}

// WithTenancyID sets the TenancyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenancyID field is set to the value of the last call.
func (b *OciAuthCredentialsApplyConfiguration) WithTenancyID(value metav1.SecretKeySelector) *OciAuthCredentialsApplyConfiguration {
	b.TenancyID = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *OciAuthCredentialsApplyConfiguration) WithRegion(value metav1.SecretKeySelector) *OciAuthCredentialsApplyConfiguration {
	b.Region = &value
	return b
}
