/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	externalsecretsv1 "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
)

// OpenBaoProviderApplyConfiguration represents a declarative configuration of the OpenBaoProvider type for use
// with apply.
//
// OpenBaoProvider configures a store to sync secrets using an OpenBao KV backend.
type OpenBaoProviderApplyConfiguration struct {
	// Auth configures how secret-manager authenticates with the OpenBao server.
	Auth *OpenBaoAuthApplyConfiguration `json:"auth,omitempty"`
	// PEM encoded CA bundle used to validate the OpenBao server certificate. If
	// this and `caProvider` are not set the system root certificates are used
	// to validate the TLS connection.
	CABundle []byte `json:"caBundle,omitempty"`
	// The provider for the CA bundle to use to validate OpenBao server
	// certificate. If this and `caBundle` are not set the system root
	// certificates are used to validate the TLS connection.
	CAProvider *CAProviderApplyConfiguration `json:"caProvider,omitempty"`
	// Name of the [OpenBao Namespace]. Namespaces is a set of features within
	// OpenBao that allows OpenBao environments to support secure multi-tenancy.
	// e.g: "ns1".
	//
	// [OpenBao Namespace]: https://openbao.org/docs/concepts/namespaces/
	Namespace *string `json:"namespace,omitempty"`
	// Server is the connection address for the OpenBao server, e.g: `https://openbao.example.com:8200`.
	Server *string `json:"server,omitempty"`
	// Path is the mount path of the OpenBao KV backend endpoint, e.g:
	// "secret". The v2 KV secret engine version specific "/data" path suffix
	// for fetching secrets from OpenBao is optional and will be appended
	// if not present in specified path.
	Path *string `json:"path,omitempty"`
	// Version is the OpenBao KV secret engine version. This can be either "v1" or
	// "v2". Version defaults to "v2".
	Version *externalsecretsv1.OpenBaoKVStoreVersion `json:"version,omitempty"`
}

// OpenBaoProviderApplyConfiguration constructs a declarative configuration of the OpenBaoProvider type for use with
// apply.
func OpenBaoProvider() *OpenBaoProviderApplyConfiguration {
	return &OpenBaoProviderApplyConfiguration{}
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *OpenBaoProviderApplyConfiguration) WithAuth(value *OpenBaoAuthApplyConfiguration) *OpenBaoProviderApplyConfiguration {
	b.Auth = value
	return b
}

// WithCABundle adds the given value to the CABundle field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CABundle field.
func (b *OpenBaoProviderApplyConfiguration) WithCABundle(values ...byte) *OpenBaoProviderApplyConfiguration {
	for i := range values {
		b.CABundle = append(b.CABundle, values[i])
	}
	return b
}

// WithCAProvider sets the CAProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAProvider field is set to the value of the last call.
func (b *OpenBaoProviderApplyConfiguration) WithCAProvider(value *CAProviderApplyConfiguration) *OpenBaoProviderApplyConfiguration {
	b.CAProvider = value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *OpenBaoProviderApplyConfiguration) WithNamespace(value string) *OpenBaoProviderApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *OpenBaoProviderApplyConfiguration) WithServer(value string) *OpenBaoProviderApplyConfiguration {
	b.Server = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *OpenBaoProviderApplyConfiguration) WithPath(value string) *OpenBaoProviderApplyConfiguration {
	b.Path = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *OpenBaoProviderApplyConfiguration) WithVersion(value externalsecretsv1.OpenBaoKVStoreVersion) *OpenBaoProviderApplyConfiguration {
	b.Version = &value
	return b
}
