/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// OracleAuthApplyConfiguration represents a declarative configuration of the OracleAuth type for use
// with apply.
//
// OracleAuth defines the authentication method for the Oracle Vault provider.
type OracleAuthApplyConfiguration struct {
	// Tenancy is the tenancy OCID where user is located.
	Tenancy *string `json:"tenancy,omitempty"`
	// User is an access OCID specific to the account.
	User *string `json:"user,omitempty"`
	// SecretRef to pass through sensitive information.
	SecretRef *OracleSecretRefApplyConfiguration `json:"secretRef,omitempty"`
}

// OracleAuthApplyConfiguration constructs a declarative configuration of the OracleAuth type for use with
// apply.
func OracleAuth() *OracleAuthApplyConfiguration {
	return &OracleAuthApplyConfiguration{}
}

// WithTenancy sets the Tenancy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tenancy field is set to the value of the last call.
func (b *OracleAuthApplyConfiguration) WithTenancy(value string) *OracleAuthApplyConfiguration {
	b.Tenancy = &value
	return b
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *OracleAuthApplyConfiguration) WithUser(value string) *OracleAuthApplyConfiguration {
	b.User = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *OracleAuthApplyConfiguration) WithSecretRef(value *OracleSecretRefApplyConfiguration) *OracleAuthApplyConfiguration {
	b.SecretRef = value
	return b
}
