/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// OvhAuthApplyConfiguration represents a declarative configuration of the OvhAuth type for use
// with apply.
//
// OvhAuth tells the controller how to authenticate to OVHcloud's Secret Manager, either using mTLS or a token.
type OvhAuthApplyConfiguration struct {
	ClientMTLS  *OvhClientMTLSApplyConfiguration  `json:"mtls,omitempty"`
	ClientToken *OvhClientTokenApplyConfiguration `json:"token,omitempty"`
}

// OvhAuthApplyConfiguration constructs a declarative configuration of the OvhAuth type for use with
// apply.
func OvhAuth() *OvhAuthApplyConfiguration {
	return &OvhAuthApplyConfiguration{}
}

// WithClientMTLS sets the ClientMTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientMTLS field is set to the value of the last call.
func (b *OvhAuthApplyConfiguration) WithClientMTLS(value *OvhClientMTLSApplyConfiguration) *OvhAuthApplyConfiguration {
	b.ClientMTLS = value
	return b
}

// WithClientToken sets the ClientToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientToken field is set to the value of the last call.
func (b *OvhAuthApplyConfiguration) WithClientToken(value *OvhClientTokenApplyConfiguration) *OvhAuthApplyConfiguration {
	b.ClientToken = value
	return b
}
