/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// OvhClientMTLSApplyConfiguration represents a declarative configuration of the OvhClientMTLS type for use
// with apply.
//
// OvhClientMTLS defines the configuration required to authenticate to OVHcloud's Secret Manager using mTLS.
type OvhClientMTLSApplyConfiguration struct {
	ClientCertificate *metav1.SecretKeySelector     `json:"certSecretRef,omitempty"`
	ClientKey         *metav1.SecretKeySelector     `json:"keySecretRef,omitempty"`
	CABundle          []byte                        `json:"caBundle,omitempty"`
	CAProvider        *CAProviderApplyConfiguration `json:"caProvider,omitempty"`
}

// OvhClientMTLSApplyConfiguration constructs a declarative configuration of the OvhClientMTLS type for use with
// apply.
func OvhClientMTLS() *OvhClientMTLSApplyConfiguration {
	return &OvhClientMTLSApplyConfiguration{}
}

// WithClientCertificate sets the ClientCertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCertificate field is set to the value of the last call.
func (b *OvhClientMTLSApplyConfiguration) WithClientCertificate(value metav1.SecretKeySelector) *OvhClientMTLSApplyConfiguration {
	b.ClientCertificate = &value
	return b
}

// WithClientKey sets the ClientKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientKey field is set to the value of the last call.
func (b *OvhClientMTLSApplyConfiguration) WithClientKey(value metav1.SecretKeySelector) *OvhClientMTLSApplyConfiguration {
	b.ClientKey = &value
	return b
}

// WithCABundle adds the given value to the CABundle field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CABundle field.
func (b *OvhClientMTLSApplyConfiguration) WithCABundle(values ...byte) *OvhClientMTLSApplyConfiguration {
	for i := range values {
		b.CABundle = append(b.CABundle, values[i])
	}
	return b
}

// WithCAProvider sets the CAProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAProvider field is set to the value of the last call.
func (b *OvhClientMTLSApplyConfiguration) WithCAProvider(value *CAProviderApplyConfiguration) *OvhClientMTLSApplyConfiguration {
	b.CAProvider = value
	return b
}
