/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// OvhClientTokenApplyConfiguration represents a declarative configuration of the OvhClientToken type for use
// with apply.
//
// OvhClientToken defines the configuration required to authenticate to OVHcloud's Secret Manager using a token.
type OvhClientTokenApplyConfiguration struct {
	ClientTokenSecret *metav1.SecretKeySelector `json:"tokenSecretRef,omitempty"`
}

// OvhClientTokenApplyConfiguration constructs a declarative configuration of the OvhClientToken type for use with
// apply.
func OvhClientToken() *OvhClientTokenApplyConfiguration {
	return &OvhClientTokenApplyConfiguration{}
}

// WithClientTokenSecret sets the ClientTokenSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientTokenSecret field is set to the value of the last call.
func (b *OvhClientTokenApplyConfiguration) WithClientTokenSecret(value metav1.SecretKeySelector) *OvhClientTokenApplyConfiguration {
	b.ClientTokenSecret = &value
	return b
}
