/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// OvhProviderApplyConfiguration represents a declarative configuration of the OvhProvider type for use
// with apply.
//
// OvhProvider holds the configuration to synchronize secrets with OVHcloud's Secret Manager.
type OvhProviderApplyConfiguration struct {
	// specifies the OKMS server endpoint.
	Server *string `json:"server,omitempty"`
	// specifies the OKMS ID.
	OkmsID *string `json:"okmsid,omitempty"`
	// Enables or disables check-and-set (CAS) (default: false).
	CasRequired *bool `json:"casRequired,omitempty"`
	// Setup a timeout in seconds when requests to the KMS are made (default: 30).
	OkmsTimeout *uint32 `json:"okmsTimeout,omitempty"`
	// Authentication method (mtls or token).
	Auth *OvhAuthApplyConfiguration `json:"auth,omitempty"`
}

// OvhProviderApplyConfiguration constructs a declarative configuration of the OvhProvider type for use with
// apply.
func OvhProvider() *OvhProviderApplyConfiguration {
	return &OvhProviderApplyConfiguration{}
}

// WithServer sets the Server field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Server field is set to the value of the last call.
func (b *OvhProviderApplyConfiguration) WithServer(value string) *OvhProviderApplyConfiguration {
	b.Server = &value
	return b
}

// WithOkmsID sets the OkmsID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OkmsID field is set to the value of the last call.
func (b *OvhProviderApplyConfiguration) WithOkmsID(value string) *OvhProviderApplyConfiguration {
	b.OkmsID = &value
	return b
}

// WithCasRequired sets the CasRequired field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CasRequired field is set to the value of the last call.
func (b *OvhProviderApplyConfiguration) WithCasRequired(value bool) *OvhProviderApplyConfiguration {
	b.CasRequired = &value
	return b
}

// WithOkmsTimeout sets the OkmsTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OkmsTimeout field is set to the value of the last call.
func (b *OvhProviderApplyConfiguration) WithOkmsTimeout(value uint32) *OvhProviderApplyConfiguration {
	b.OkmsTimeout = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *OvhProviderApplyConfiguration) WithAuth(value *OvhAuthApplyConfiguration) *OvhProviderApplyConfiguration {
	b.Auth = value
	return b
}
