/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// PasswordDepotProviderApplyConfiguration represents a declarative configuration of the PasswordDepotProvider type for use
// with apply.
//
// PasswordDepotProvider configures a store to sync secrets with a Password Depot instance.
type PasswordDepotProviderApplyConfiguration struct {
	// URL configures the Password Depot instance URL.
	Host *string `json:"host,omitempty"`
	// Database to use as source
	Database *string `json:"database,omitempty"`
	// Auth configures how secret-manager authenticates with a Password Depot instance.
	Auth *PasswordDepotAuthApplyConfiguration `json:"auth,omitempty"`
}

// PasswordDepotProviderApplyConfiguration constructs a declarative configuration of the PasswordDepotProvider type for use with
// apply.
func PasswordDepotProvider() *PasswordDepotProviderApplyConfiguration {
	return &PasswordDepotProviderApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *PasswordDepotProviderApplyConfiguration) WithHost(value string) *PasswordDepotProviderApplyConfiguration {
	b.Host = &value
	return b
}

// WithDatabase sets the Database field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Database field is set to the value of the last call.
func (b *PasswordDepotProviderApplyConfiguration) WithDatabase(value string) *PasswordDepotProviderApplyConfiguration {
	b.Database = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *PasswordDepotProviderApplyConfiguration) WithAuth(value *PasswordDepotAuthApplyConfiguration) *PasswordDepotProviderApplyConfiguration {
	b.Auth = value
	return b
}
