/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// PassboltProviderApplyConfiguration represents a declarative configuration of the PassboltProvider type for use
// with apply.
//
// PassboltProvider provides access to Passbolt secrets manager.
// See: https://www.passbolt.com.
type PassboltProviderApplyConfiguration struct {
	// Auth defines the information necessary to authenticate against Passbolt Server
	Auth *PassboltAuthApplyConfiguration `json:"auth,omitempty"`
	// Host defines the Passbolt Server to connect to
	Host *string `json:"host,omitempty"`
	// PEM encoded CA bundle used to validate Passbolt server certificate. Only used
	// if the Host URL is using HTTPS protocol. If not set the system root certificates
	// are used to validate the TLS connection.
	CABundle []byte `json:"caBundle,omitempty"`
	// The provider for the CA bundle to use to validate Passbolt server certificate.
	CAProvider *CAProviderApplyConfiguration `json:"caProvider,omitempty"`
}

// PassboltProviderApplyConfiguration constructs a declarative configuration of the PassboltProvider type for use with
// apply.
func PassboltProvider() *PassboltProviderApplyConfiguration {
	return &PassboltProviderApplyConfiguration{}
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *PassboltProviderApplyConfiguration) WithAuth(value *PassboltAuthApplyConfiguration) *PassboltProviderApplyConfiguration {
	b.Auth = value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *PassboltProviderApplyConfiguration) WithHost(value string) *PassboltProviderApplyConfiguration {
	b.Host = &value
	return b
}

// WithCABundle adds the given value to the CABundle field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CABundle field.
func (b *PassboltProviderApplyConfiguration) WithCABundle(values ...byte) *PassboltProviderApplyConfiguration {
	for i := range values {
		b.CABundle = append(b.CABundle, values[i])
	}
	return b
}

// WithCAProvider sets the CAProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAProvider field is set to the value of the last call.
func (b *PassboltProviderApplyConfiguration) WithCAProvider(value *CAProviderApplyConfiguration) *PassboltProviderApplyConfiguration {
	b.CAProvider = value
	return b
}
