/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// PulumiAuthApplyConfiguration represents a declarative configuration of the PulumiAuth type for use
// with apply.
//
// PulumiAuth configures authentication with the Pulumi API.
// Exactly one of accessToken or oidcConfig must be specified.
type PulumiAuthApplyConfiguration struct {
	// AccessToken authenticates using a Pulumi access token stored in a Kubernetes Secret.
	AccessToken *PulumiProviderSecretRefApplyConfiguration `json:"accessToken,omitempty"`
	// OIDCConfig authenticates using Kubernetes ServiceAccount tokens via OIDC.
	OIDCConfig *PulumiOIDCAuthApplyConfiguration `json:"oidcConfig,omitempty"`
}

// PulumiAuthApplyConfiguration constructs a declarative configuration of the PulumiAuth type for use with
// apply.
func PulumiAuth() *PulumiAuthApplyConfiguration {
	return &PulumiAuthApplyConfiguration{}
}

// WithAccessToken sets the AccessToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessToken field is set to the value of the last call.
func (b *PulumiAuthApplyConfiguration) WithAccessToken(value *PulumiProviderSecretRefApplyConfiguration) *PulumiAuthApplyConfiguration {
	b.AccessToken = value
	return b
}

// WithOIDCConfig sets the OIDCConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OIDCConfig field is set to the value of the last call.
func (b *PulumiAuthApplyConfiguration) WithOIDCConfig(value *PulumiOIDCAuthApplyConfiguration) *PulumiAuthApplyConfiguration {
	b.OIDCConfig = value
	return b
}
