/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// PulumiProviderApplyConfiguration represents a declarative configuration of the PulumiProvider type for use
// with apply.
//
// PulumiProvider defines configuration for accessing secrets from Pulumi ESC.
type PulumiProviderApplyConfiguration struct {
	// APIURL is the URL of the Pulumi API.
	APIURL *string `json:"apiUrl,omitempty"`
	// Auth configures how the Operator authenticates with the Pulumi API.
	// Either auth or the deprecated accessToken field must be specified.
	Auth *PulumiAuthApplyConfiguration `json:"auth,omitempty"`
	// Organization are a space to collaborate on shared projects and stacks.
	// To create a new organization, visit https://app.pulumi.com/ and click "New Organization".
	Organization *string `json:"organization,omitempty"`
	// Project is the name of the Pulumi ESC project the environment belongs to.
	Project *string `json:"project,omitempty"`
	// Environment are YAML documents composed of static key-value pairs, programmatic expressions,
	// dynamically retrieved values from supported providers including all major clouds,
	// and other Pulumi ESC environments.
	// To create a new environment, visit https://www.pulumi.com/docs/esc/environments/ for more information.
	Environment *string `json:"environment,omitempty"`
	// AccessToken is the access tokens to sign in to the Pulumi Cloud Console.
	//
	// Deprecated: Use auth.accessToken instead.
	AccessToken *PulumiProviderSecretRefApplyConfiguration `json:"accessToken,omitempty"`
}

// PulumiProviderApplyConfiguration constructs a declarative configuration of the PulumiProvider type for use with
// apply.
func PulumiProvider() *PulumiProviderApplyConfiguration {
	return &PulumiProviderApplyConfiguration{}
}

// WithAPIURL sets the APIURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIURL field is set to the value of the last call.
func (b *PulumiProviderApplyConfiguration) WithAPIURL(value string) *PulumiProviderApplyConfiguration {
	b.APIURL = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *PulumiProviderApplyConfiguration) WithAuth(value *PulumiAuthApplyConfiguration) *PulumiProviderApplyConfiguration {
	b.Auth = value
	return b
}

// WithOrganization sets the Organization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Organization field is set to the value of the last call.
func (b *PulumiProviderApplyConfiguration) WithOrganization(value string) *PulumiProviderApplyConfiguration {
	b.Organization = &value
	return b
}

// WithProject sets the Project field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Project field is set to the value of the last call.
func (b *PulumiProviderApplyConfiguration) WithProject(value string) *PulumiProviderApplyConfiguration {
	b.Project = &value
	return b
}

// WithEnvironment sets the Environment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Environment field is set to the value of the last call.
func (b *PulumiProviderApplyConfiguration) WithEnvironment(value string) *PulumiProviderApplyConfiguration {
	b.Environment = &value
	return b
}

// WithAccessToken sets the AccessToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessToken field is set to the value of the last call.
func (b *PulumiProviderApplyConfiguration) WithAccessToken(value *PulumiProviderSecretRefApplyConfiguration) *PulumiProviderApplyConfiguration {
	b.AccessToken = value
	return b
}
