/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// ScalewayProviderApplyConfiguration represents a declarative configuration of the ScalewayProvider type for use
// with apply.
//
// ScalewayProvider defines the configuration for the Scaleway Secret Manager provider.
type ScalewayProviderApplyConfiguration struct {
	// APIURL is the url of the api to use. Defaults to https://api.scaleway.com
	APIURL *string `json:"apiUrl,omitempty"`
	// Region where your secrets are located: https://developers.scaleway.com/en/quickstart/#region-and-zone
	Region *string `json:"region,omitempty"`
	// ProjectID is the id of your project, which you can find in the console: https://console.scaleway.com/project/settings
	ProjectID *string `json:"projectId,omitempty"`
	// AccessKey is the non-secret part of the api key.
	AccessKey *ScalewayProviderSecretRefApplyConfiguration `json:"accessKey,omitempty"`
	// SecretKey is the non-secret part of the api key.
	SecretKey *ScalewayProviderSecretRefApplyConfiguration `json:"secretKey,omitempty"`
}

// ScalewayProviderApplyConfiguration constructs a declarative configuration of the ScalewayProvider type for use with
// apply.
func ScalewayProvider() *ScalewayProviderApplyConfiguration {
	return &ScalewayProviderApplyConfiguration{}
}

// WithAPIURL sets the APIURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIURL field is set to the value of the last call.
func (b *ScalewayProviderApplyConfiguration) WithAPIURL(value string) *ScalewayProviderApplyConfiguration {
	b.APIURL = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *ScalewayProviderApplyConfiguration) WithRegion(value string) *ScalewayProviderApplyConfiguration {
	b.Region = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *ScalewayProviderApplyConfiguration) WithProjectID(value string) *ScalewayProviderApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithAccessKey sets the AccessKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessKey field is set to the value of the last call.
func (b *ScalewayProviderApplyConfiguration) WithAccessKey(value *ScalewayProviderSecretRefApplyConfiguration) *ScalewayProviderApplyConfiguration {
	b.AccessKey = value
	return b
}

// WithSecretKey sets the SecretKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretKey field is set to the value of the last call.
func (b *ScalewayProviderApplyConfiguration) WithSecretKey(value *ScalewayProviderSecretRefApplyConfiguration) *ScalewayProviderApplyConfiguration {
	b.SecretKey = value
	return b
}
