/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// SecretsManagerApplyConfiguration represents a declarative configuration of the SecretsManager type for use
// with apply.
//
// SecretsManager defines how the provider behaves when interacting with AWS
// SecretsManager. Some of these settings are only applicable to controlling how
// secrets are deleted, and hence only apply to PushSecret (and only when
// deletionPolicy is set to Delete).
type SecretsManagerApplyConfiguration struct {
	// Specifies whether to delete the secret without any recovery window. You
	// can't use both this parameter and RecoveryWindowInDays in the same call.
	// If you don't use either, then by default Secrets Manager uses a 30 day
	// recovery window.
	// see: https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteSecret.html#SecretsManager-DeleteSecret-request-ForceDeleteWithoutRecovery
	ForceDeleteWithoutRecovery *bool `json:"forceDeleteWithoutRecovery,omitempty"`
	// The number of days from 7 to 30 that Secrets Manager waits before
	// permanently deleting the secret. You can't use both this parameter and
	// ForceDeleteWithoutRecovery in the same call. If you don't use either,
	// then by default Secrets Manager uses a 30-day recovery window.
	// see: https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteSecret.html#SecretsManager-DeleteSecret-request-RecoveryWindowInDays
	RecoveryWindowInDays *int64 `json:"recoveryWindowInDays,omitempty"`
}

// SecretsManagerApplyConfiguration constructs a declarative configuration of the SecretsManager type for use with
// apply.
func SecretsManager() *SecretsManagerApplyConfiguration {
	return &SecretsManagerApplyConfiguration{}
}

// WithForceDeleteWithoutRecovery sets the ForceDeleteWithoutRecovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForceDeleteWithoutRecovery field is set to the value of the last call.
func (b *SecretsManagerApplyConfiguration) WithForceDeleteWithoutRecovery(value bool) *SecretsManagerApplyConfiguration {
	b.ForceDeleteWithoutRecovery = &value
	return b
}

// WithRecoveryWindowInDays sets the RecoveryWindowInDays field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecoveryWindowInDays field is set to the value of the last call.
func (b *SecretsManagerApplyConfiguration) WithRecoveryWindowInDays(value int64) *SecretsManagerApplyConfiguration {
	b.RecoveryWindowInDays = &value
	return b
}
