/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// SecretStoreRefApplyConfiguration represents a declarative configuration of the SecretStoreRef type for use
// with apply.
//
// SecretStoreRef defines which SecretStore to fetch the ExternalSecret data.
type SecretStoreRefApplyConfiguration struct {
	// Name of the SecretStore resource
	Name *string `json:"name,omitempty"`
	// Kind of the SecretStore resource (SecretStore or ClusterSecretStore)
	// Defaults to `SecretStore`
	Kind *string `json:"kind,omitempty"`
}

// SecretStoreRefApplyConfiguration constructs a declarative configuration of the SecretStoreRef type for use with
// apply.
func SecretStoreRef() *SecretStoreRefApplyConfiguration {
	return &SecretStoreRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SecretStoreRefApplyConfiguration) WithName(value string) *SecretStoreRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SecretStoreRefApplyConfiguration) WithKind(value string) *SecretStoreRefApplyConfiguration {
	b.Kind = &value
	return b
}
