/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// SecretStoreProviderApplyConfiguration represents a declarative configuration of the SecretStoreProvider type for use
// with apply.
//
// SecretStoreProvider contains the provider-specific configuration.
type SecretStoreProviderApplyConfiguration struct {
	// AWS configures this store to sync secrets using AWS Secret Manager provider
	AWS *AWSProviderApplyConfiguration `json:"aws,omitempty"`
	// AzureKV configures this store to sync secrets using Azure Key Vault provider
	AzureKV *AzureKVProviderApplyConfiguration `json:"azurekv,omitempty"`
	// Akeyless configures this store to sync secrets using Akeyless Vault provider
	Akeyless *AkeylessProviderApplyConfiguration `json:"akeyless,omitempty"`
	// BitwardenSecretsManager configures this store to sync secrets using BitwardenSecretsManager provider
	BitwardenSecretsManager *BitwardenSecretsManagerProviderApplyConfiguration `json:"bitwardensecretsmanager,omitempty"`
	// Vault configures this store to sync secrets using the HashiCorp Vault provider.
	Vault *VaultProviderApplyConfiguration `json:"vault,omitempty"`
	// OVHcloud configures this store to sync secrets using the OVHcloud provider.
	OVHcloud *OvhProviderApplyConfiguration `json:"ovh,omitempty"`
	// GCPSM configures this store to sync secrets using Google Cloud Platform Secret Manager provider
	GCPSM *GCPSMProviderApplyConfiguration `json:"gcpsm,omitempty"`
	// Oracle configures this store to sync secrets using Oracle Vault provider
	Oracle *OracleProviderApplyConfiguration `json:"oracle,omitempty"`
	// IBM configures this store to sync secrets using IBM Cloud provider
	IBM *IBMProviderApplyConfiguration `json:"ibm,omitempty"`
	// YandexCertificateManager configures this store to sync secrets using Yandex Certificate Manager provider
	YandexCertificateManager *YandexCertificateManagerProviderApplyConfiguration `json:"yandexcertificatemanager,omitempty"`
	// YandexLockbox configures this store to sync secrets using Yandex Lockbox provider
	YandexLockbox *YandexLockboxProviderApplyConfiguration `json:"yandexlockbox,omitempty"`
	// Github configures this store to push GitHub Actions secrets using the GitHub API provider.
	// Note: This provider only supports write operations (PushSecret) and cannot fetch secrets from GitHub
	Github *GithubProviderApplyConfiguration `json:"github,omitempty"`
	// GitLab configures this store to sync secrets using GitLab Variables provider
	Gitlab *GitlabProviderApplyConfiguration `json:"gitlab,omitempty"`
	// OnePassword configures this store to sync secrets using the 1Password Cloud provider
	OnePassword *OnePasswordProviderApplyConfiguration `json:"onepassword,omitempty"`
	// OnePasswordSDK configures this store to use 1Password's new Go SDK to sync secrets.
	OnePasswordSDK *OnePasswordSDKProviderApplyConfiguration `json:"onepasswordSDK,omitempty"`
	// Webhook configures this store to sync secrets using a generic templated webhook
	Webhook *WebhookProviderApplyConfiguration `json:"webhook,omitempty"`
	// Kubernetes configures this store to sync secrets using a Kubernetes cluster provider
	Kubernetes *KubernetesProviderApplyConfiguration `json:"kubernetes,omitempty"`
	// Fake configures a store with static key/value pairs
	Fake *FakeProviderApplyConfiguration `json:"fake,omitempty"`
	// Senhasegura configures this store to sync secrets using senhasegura provider
	Senhasegura *SenhaseguraProviderApplyConfiguration `json:"senhasegura,omitempty"`
	// Scaleway configures this store to sync secrets using the Scaleway provider.
	Scaleway *ScalewayProviderApplyConfiguration `json:"scaleway,omitempty"`
	// Doppler configures this store to sync secrets using the Doppler provider
	Doppler *DopplerProviderApplyConfiguration `json:"doppler,omitempty"`
	// Previder configures this store to sync secrets using the Previder provider
	Previder *PreviderProviderApplyConfiguration `json:"previder,omitempty"`
	// Onboardbase configures this store to sync secrets using the Onboardbase provider
	Onboardbase *OnboardbaseProviderApplyConfiguration `json:"onboardbase,omitempty"`
	// KeeperSecurity configures this store to sync secrets using the KeeperSecurity provider
	KeeperSecurity *KeeperSecurityProviderApplyConfiguration `json:"keepersecurity,omitempty"`
	// Conjur configures this store to sync secrets using conjur provider
	Conjur *ConjurProviderApplyConfiguration `json:"conjur,omitempty"`
	// Delinea DevOps Secrets Vault
	// https://docs.delinea.com/online-help/products/devops-secrets-vault/current
	Delinea *DelineaProviderApplyConfiguration `json:"delinea,omitempty"`
	// SecretServer configures this store to sync secrets using SecretServer provider
	// https://docs.delinea.com/online-help/secret-server/start.htm
	SecretServer *SecretServerProviderApplyConfiguration `json:"secretserver,omitempty"`
	// Chef configures this store to sync secrets with chef server
	Chef *ChefProviderApplyConfiguration `json:"chef,omitempty"`
	// Pulumi configures this store to sync secrets using the Pulumi provider
	Pulumi *PulumiProviderApplyConfiguration `json:"pulumi,omitempty"`
	// Fortanix configures this store to sync secrets using the Fortanix provider
	Fortanix      *FortanixProviderApplyConfiguration      `json:"fortanix,omitempty"`
	PasswordDepot *PasswordDepotProviderApplyConfiguration `json:"passworddepot,omitempty"`
	Passbolt      *PassboltProviderApplyConfiguration      `json:"passbolt,omitempty"`
	// DVLS configures this store to sync secrets using Devolutions Server provider
	DVLS *DVLSProviderApplyConfiguration `json:"dvls,omitempty"`
	// Infisical configures this store to sync secrets using the Infisical provider
	Infisical *InfisicalProviderApplyConfiguration `json:"infisical,omitempty"`
	// Beyondtrust configures this store to sync secrets using Password Safe provider.
	Beyondtrust *BeyondtrustProviderApplyConfiguration `json:"beyondtrust,omitempty"`
	// BeyondtrustWorkloadCredentials configures this store to sync secrets using the BeyondTrust Workload Credentials provider.
	BeyondtrustWorkloadCredentials *BeyondtrustWorkloadCredentialsProviderApplyConfiguration `json:"beyondtrustworkloadcredentials,omitempty"`
	// CloudruSM configures this store to sync secrets using the Cloud.ru Secret Manager provider
	CloudruSM *CloudruSMProviderApplyConfiguration `json:"cloudrusm,omitempty"`
	// Volcengine configures this store to sync secrets using the Volcengine provider
	Volcengine *VolcengineProviderApplyConfiguration `json:"volcengine,omitempty"`
	// Ngrok configures this store to sync secrets using the ngrok provider.
	Ngrok *NgrokProviderApplyConfiguration `json:"ngrok,omitempty"`
	// Barbican configures this store to sync secrets using the OpenStack Barbican provider
	Barbican *BarbicanProviderApplyConfiguration `json:"barbican,omitempty"`
	// NebiusMysterybox configures this store to sync secrets using NebiusMysterybox provider
	NebiusMysterybox *NebiusMysteryboxProviderApplyConfiguration `json:"nebiusmysterybox,omitempty"`
	// OpenBao configures this store to sync secrets using the OpenBao provider.
	OpenBao *OpenBaoProviderApplyConfiguration `json:"openBao,omitempty"`
}

// SecretStoreProviderApplyConfiguration constructs a declarative configuration of the SecretStoreProvider type for use with
// apply.
func SecretStoreProvider() *SecretStoreProviderApplyConfiguration {
	return &SecretStoreProviderApplyConfiguration{}
}

// WithAWS sets the AWS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AWS field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithAWS(value *AWSProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.AWS = value
	return b
}

// WithAzureKV sets the AzureKV field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AzureKV field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithAzureKV(value *AzureKVProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.AzureKV = value
	return b
}

// WithAkeyless sets the Akeyless field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Akeyless field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithAkeyless(value *AkeylessProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Akeyless = value
	return b
}

// WithBitwardenSecretsManager sets the BitwardenSecretsManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BitwardenSecretsManager field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithBitwardenSecretsManager(value *BitwardenSecretsManagerProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.BitwardenSecretsManager = value
	return b
}

// WithVault sets the Vault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vault field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithVault(value *VaultProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Vault = value
	return b
}

// WithOVHcloud sets the OVHcloud field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OVHcloud field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithOVHcloud(value *OvhProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.OVHcloud = value
	return b
}

// WithGCPSM sets the GCPSM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GCPSM field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithGCPSM(value *GCPSMProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.GCPSM = value
	return b
}

// WithOracle sets the Oracle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Oracle field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithOracle(value *OracleProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Oracle = value
	return b
}

// WithIBM sets the IBM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IBM field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithIBM(value *IBMProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.IBM = value
	return b
}

// WithYandexCertificateManager sets the YandexCertificateManager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the YandexCertificateManager field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithYandexCertificateManager(value *YandexCertificateManagerProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.YandexCertificateManager = value
	return b
}

// WithYandexLockbox sets the YandexLockbox field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the YandexLockbox field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithYandexLockbox(value *YandexLockboxProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.YandexLockbox = value
	return b
}

// WithGithub sets the Github field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Github field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithGithub(value *GithubProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Github = value
	return b
}

// WithGitlab sets the Gitlab field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gitlab field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithGitlab(value *GitlabProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Gitlab = value
	return b
}

// WithOnePassword sets the OnePassword field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnePassword field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithOnePassword(value *OnePasswordProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.OnePassword = value
	return b
}

// WithOnePasswordSDK sets the OnePasswordSDK field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnePasswordSDK field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithOnePasswordSDK(value *OnePasswordSDKProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.OnePasswordSDK = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithWebhook(value *WebhookProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Webhook = value
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithKubernetes(value *KubernetesProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Kubernetes = value
	return b
}

// WithFake sets the Fake field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fake field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithFake(value *FakeProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Fake = value
	return b
}

// WithSenhasegura sets the Senhasegura field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Senhasegura field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithSenhasegura(value *SenhaseguraProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Senhasegura = value
	return b
}

// WithScaleway sets the Scaleway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scaleway field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithScaleway(value *ScalewayProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Scaleway = value
	return b
}

// WithDoppler sets the Doppler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Doppler field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithDoppler(value *DopplerProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Doppler = value
	return b
}

// WithPrevider sets the Previder field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Previder field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithPrevider(value *PreviderProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Previder = value
	return b
}

// WithOnboardbase sets the Onboardbase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Onboardbase field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithOnboardbase(value *OnboardbaseProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Onboardbase = value
	return b
}

// WithKeeperSecurity sets the KeeperSecurity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeeperSecurity field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithKeeperSecurity(value *KeeperSecurityProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.KeeperSecurity = value
	return b
}

// WithConjur sets the Conjur field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Conjur field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithConjur(value *ConjurProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Conjur = value
	return b
}

// WithDelinea sets the Delinea field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Delinea field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithDelinea(value *DelineaProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Delinea = value
	return b
}

// WithSecretServer sets the SecretServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretServer field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithSecretServer(value *SecretServerProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.SecretServer = value
	return b
}

// WithChef sets the Chef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Chef field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithChef(value *ChefProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Chef = value
	return b
}

// WithPulumi sets the Pulumi field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pulumi field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithPulumi(value *PulumiProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Pulumi = value
	return b
}

// WithFortanix sets the Fortanix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fortanix field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithFortanix(value *FortanixProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Fortanix = value
	return b
}

// WithPasswordDepot sets the PasswordDepot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PasswordDepot field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithPasswordDepot(value *PasswordDepotProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.PasswordDepot = value
	return b
}

// WithPassbolt sets the Passbolt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Passbolt field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithPassbolt(value *PassboltProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Passbolt = value
	return b
}

// WithDVLS sets the DVLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DVLS field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithDVLS(value *DVLSProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.DVLS = value
	return b
}

// WithInfisical sets the Infisical field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Infisical field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithInfisical(value *InfisicalProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Infisical = value
	return b
}

// WithBeyondtrust sets the Beyondtrust field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Beyondtrust field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithBeyondtrust(value *BeyondtrustProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Beyondtrust = value
	return b
}

// WithBeyondtrustWorkloadCredentials sets the BeyondtrustWorkloadCredentials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BeyondtrustWorkloadCredentials field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithBeyondtrustWorkloadCredentials(value *BeyondtrustWorkloadCredentialsProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.BeyondtrustWorkloadCredentials = value
	return b
}

// WithCloudruSM sets the CloudruSM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudruSM field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithCloudruSM(value *CloudruSMProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.CloudruSM = value
	return b
}

// WithVolcengine sets the Volcengine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Volcengine field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithVolcengine(value *VolcengineProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Volcengine = value
	return b
}

// WithNgrok sets the Ngrok field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ngrok field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithNgrok(value *NgrokProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Ngrok = value
	return b
}

// WithBarbican sets the Barbican field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Barbican field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithBarbican(value *BarbicanProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.Barbican = value
	return b
}

// WithNebiusMysterybox sets the NebiusMysterybox field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NebiusMysterybox field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithNebiusMysterybox(value *NebiusMysteryboxProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.NebiusMysterybox = value
	return b
}

// WithOpenBao sets the OpenBao field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenBao field is set to the value of the last call.
func (b *SecretStoreProviderApplyConfiguration) WithOpenBao(value *OpenBaoProviderApplyConfiguration) *SecretStoreProviderApplyConfiguration {
	b.OpenBao = value
	return b
}
