/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	externalsecretsv1 "github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
)

// SenhaseguraProviderApplyConfiguration represents a declarative configuration of the SenhaseguraProvider type for use
// with apply.
//
// SenhaseguraProvider setup a store to sync secrets with senhasegura.
type SenhaseguraProviderApplyConfiguration struct {
	// URL of senhasegura
	URL *string `json:"url,omitempty"`
	// Module defines which senhasegura module should be used to get secrets
	Module *externalsecretsv1.SenhaseguraModuleType `json:"module,omitempty"`
	// Auth defines parameters to authenticate in senhasegura
	Auth *SenhaseguraAuthApplyConfiguration `json:"auth,omitempty"`
	// IgnoreSslCertificate defines if SSL certificate must be ignored
	IgnoreSslCertificate *bool `json:"ignoreSslCertificate,omitempty"`
}

// SenhaseguraProviderApplyConfiguration constructs a declarative configuration of the SenhaseguraProvider type for use with
// apply.
func SenhaseguraProvider() *SenhaseguraProviderApplyConfiguration {
	return &SenhaseguraProviderApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *SenhaseguraProviderApplyConfiguration) WithURL(value string) *SenhaseguraProviderApplyConfiguration {
	b.URL = &value
	return b
}

// WithModule sets the Module field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Module field is set to the value of the last call.
func (b *SenhaseguraProviderApplyConfiguration) WithModule(value externalsecretsv1.SenhaseguraModuleType) *SenhaseguraProviderApplyConfiguration {
	b.Module = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *SenhaseguraProviderApplyConfiguration) WithAuth(value *SenhaseguraAuthApplyConfiguration) *SenhaseguraProviderApplyConfiguration {
	b.Auth = value
	return b
}

// WithIgnoreSslCertificate sets the IgnoreSslCertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreSslCertificate field is set to the value of the last call.
func (b *SenhaseguraProviderApplyConfiguration) WithIgnoreSslCertificate(value bool) *SenhaseguraProviderApplyConfiguration {
	b.IgnoreSslCertificate = &value
	return b
}
