/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// StoreGeneratorSourceRefApplyConfiguration represents a declarative configuration of the StoreGeneratorSourceRef type for use
// with apply.
//
// StoreGeneratorSourceRef allows you to override the source
// from which the secret will be pulled from.
// You can define at maximum one property.
type StoreGeneratorSourceRefApplyConfiguration struct {
	SecretStoreRef *SecretStoreRefApplyConfiguration `json:"storeRef,omitempty"`
	// GeneratorRef points to a generator custom resource.
	GeneratorRef *GeneratorRefApplyConfiguration `json:"generatorRef,omitempty"`
}

// StoreGeneratorSourceRefApplyConfiguration constructs a declarative configuration of the StoreGeneratorSourceRef type for use with
// apply.
func StoreGeneratorSourceRef() *StoreGeneratorSourceRefApplyConfiguration {
	return &StoreGeneratorSourceRefApplyConfiguration{}
}

// WithSecretStoreRef sets the SecretStoreRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretStoreRef field is set to the value of the last call.
func (b *StoreGeneratorSourceRefApplyConfiguration) WithSecretStoreRef(value *SecretStoreRefApplyConfiguration) *StoreGeneratorSourceRefApplyConfiguration {
	b.SecretStoreRef = value
	return b
}

// WithGeneratorRef sets the GeneratorRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GeneratorRef field is set to the value of the last call.
func (b *StoreGeneratorSourceRefApplyConfiguration) WithGeneratorRef(value *GeneratorRefApplyConfiguration) *StoreGeneratorSourceRefApplyConfiguration {
	b.GeneratorRef = value
	return b
}
