/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// VaultAuthApplyConfiguration represents a declarative configuration of the VaultAuth type for use
// with apply.
//
// VaultAuth is the configuration used to authenticate with a Vault server.
// Only one of `tokenSecretRef`, `appRole`,  `kubernetes`, `ldap`, `userPass`, `jwt`, `cert`, `iam` or `gcp`
// can be specified. A namespace to authenticate against can optionally be specified.
type VaultAuthApplyConfiguration struct {
	// Name of the vault namespace to authenticate to. This can be different than the namespace your secret is in.
	// Namespaces is a set of features within Vault Enterprise that allows
	// Vault environments to support Secure Multi-tenancy. e.g: "ns1".
	// More about namespaces can be found here https://www.vaultproject.io/docs/enterprise/namespaces
	// This will default to Vault.Namespace field if set, or empty otherwise
	Namespace *string `json:"namespace,omitempty"`
	// TokenSecretRef authenticates with Vault by presenting a token.
	TokenSecretRef *metav1.SecretKeySelector `json:"tokenSecretRef,omitempty"`
	// AppRole authenticates with Vault using the App Role auth mechanism,
	// with the role and secret stored in a Kubernetes Secret resource.
	AppRole *VaultAppRoleApplyConfiguration `json:"appRole,omitempty"`
	// Kubernetes authenticates with Vault by passing the ServiceAccount
	// token stored in the named Secret resource to the Vault server.
	Kubernetes *VaultKubernetesAuthApplyConfiguration `json:"kubernetes,omitempty"`
	// Ldap authenticates with Vault by passing username/password pair using
	// the LDAP authentication method
	Ldap *VaultLdapAuthApplyConfiguration `json:"ldap,omitempty"`
	// Jwt authenticates with Vault by passing role and JWT token using the
	// JWT/OIDC authentication method
	Jwt *VaultJwtAuthApplyConfiguration `json:"jwt,omitempty"`
	// Cert authenticates with TLS Certificates by passing client certificate, private key and ca certificate
	// Cert authentication method
	Cert *VaultCertAuthApplyConfiguration `json:"cert,omitempty"`
	// Iam authenticates with vault by passing a special AWS request signed with AWS IAM credentials
	// AWS IAM authentication method
	Iam *VaultIamAuthApplyConfiguration `json:"iam,omitempty"`
	// UserPass authenticates with Vault by passing username/password pair
	UserPass *VaultUserPassAuthApplyConfiguration `json:"userPass,omitempty"`
	// Gcp authenticates with Vault using Google Cloud Platform authentication method
	// GCP authentication method
	GCP *VaultGCPAuthApplyConfiguration `json:"gcp,omitempty"`
}

// VaultAuthApplyConfiguration constructs a declarative configuration of the VaultAuth type for use with
// apply.
func VaultAuth() *VaultAuthApplyConfiguration {
	return &VaultAuthApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithNamespace(value string) *VaultAuthApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithTokenSecretRef sets the TokenSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenSecretRef field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithTokenSecretRef(value metav1.SecretKeySelector) *VaultAuthApplyConfiguration {
	b.TokenSecretRef = &value
	return b
}

// WithAppRole sets the AppRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppRole field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithAppRole(value *VaultAppRoleApplyConfiguration) *VaultAuthApplyConfiguration {
	b.AppRole = value
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithKubernetes(value *VaultKubernetesAuthApplyConfiguration) *VaultAuthApplyConfiguration {
	b.Kubernetes = value
	return b
}

// WithLdap sets the Ldap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ldap field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithLdap(value *VaultLdapAuthApplyConfiguration) *VaultAuthApplyConfiguration {
	b.Ldap = value
	return b
}

// WithJwt sets the Jwt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Jwt field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithJwt(value *VaultJwtAuthApplyConfiguration) *VaultAuthApplyConfiguration {
	b.Jwt = value
	return b
}

// WithCert sets the Cert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cert field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithCert(value *VaultCertAuthApplyConfiguration) *VaultAuthApplyConfiguration {
	b.Cert = value
	return b
}

// WithIam sets the Iam field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Iam field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithIam(value *VaultIamAuthApplyConfiguration) *VaultAuthApplyConfiguration {
	b.Iam = value
	return b
}

// WithUserPass sets the UserPass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserPass field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithUserPass(value *VaultUserPassAuthApplyConfiguration) *VaultAuthApplyConfiguration {
	b.UserPass = value
	return b
}

// WithGCP sets the GCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GCP field is set to the value of the last call.
func (b *VaultAuthApplyConfiguration) WithGCP(value *VaultGCPAuthApplyConfiguration) *VaultAuthApplyConfiguration {
	b.GCP = value
	return b
}
