/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// VaultCertAuthApplyConfiguration represents a declarative configuration of the VaultCertAuth type for use
// with apply.
//
// VaultCertAuth authenticates with Vault using the JWT/OIDC authentication
// method, with the role name and token stored in a Kubernetes Secret resource.
type VaultCertAuthApplyConfiguration struct {
	// Path where the Certificate authentication backend is mounted
	// in Vault, e.g: "cert"
	Path *string `json:"path,omitempty"`
	// VaultRole specifies the Vault role to use for TLS certificate authentication.
	VaultRole *string `json:"vaultRole,omitempty"`
	// ClientCert is a certificate to authenticate using the Cert Vault
	// authentication method
	ClientCert *metav1.SecretKeySelector `json:"clientCert,omitempty"`
	// SecretRef to a key in a Secret resource containing client private key to
	// authenticate with Vault using the Cert authentication method
	SecretRef *metav1.SecretKeySelector `json:"secretRef,omitempty"`
}

// VaultCertAuthApplyConfiguration constructs a declarative configuration of the VaultCertAuth type for use with
// apply.
func VaultCertAuth() *VaultCertAuthApplyConfiguration {
	return &VaultCertAuthApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *VaultCertAuthApplyConfiguration) WithPath(value string) *VaultCertAuthApplyConfiguration {
	b.Path = &value
	return b
}

// WithVaultRole sets the VaultRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VaultRole field is set to the value of the last call.
func (b *VaultCertAuthApplyConfiguration) WithVaultRole(value string) *VaultCertAuthApplyConfiguration {
	b.VaultRole = &value
	return b
}

// WithClientCert sets the ClientCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientCert field is set to the value of the last call.
func (b *VaultCertAuthApplyConfiguration) WithClientCert(value metav1.SecretKeySelector) *VaultCertAuthApplyConfiguration {
	b.ClientCert = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *VaultCertAuthApplyConfiguration) WithSecretRef(value metav1.SecretKeySelector) *VaultCertAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}
