/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/external-secrets/external-secrets/apis/meta/v1"
)

// VaultAppRoleApplyConfiguration represents a declarative configuration of the VaultAppRole type for use
// with apply.
//
// VaultAppRole authenticates with Vault using the App Role auth mechanism,
// with the role and secret stored in a Kubernetes Secret resource.
type VaultAppRoleApplyConfiguration struct {
	// Path where the App Role authentication backend is mounted
	// in Vault, e.g: "approle"
	Path *string `json:"path,omitempty"`
	// RoleID configured in the App Role authentication backend when setting
	// up the authentication backend in Vault.
	RoleID *string `json:"roleId,omitempty"`
	// Reference to a key in a Secret that contains the App Role ID used
	// to authenticate with Vault.
	// The `key` field must be specified and denotes which entry within the Secret
	// resource is used as the app role id.
	RoleRef *metav1.SecretKeySelector `json:"roleRef,omitempty"`
	// Reference to a key in a Secret that contains the App Role secret used
	// to authenticate with Vault.
	// The `key` field must be specified and denotes which entry within the Secret
	// resource is used as the app role secret.
	SecretRef *metav1.SecretKeySelector `json:"secretRef,omitempty"`
}

// VaultAppRoleApplyConfiguration constructs a declarative configuration of the VaultAppRole type for use with
// apply.
func VaultAppRole() *VaultAppRoleApplyConfiguration {
	return &VaultAppRoleApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *VaultAppRoleApplyConfiguration) WithPath(value string) *VaultAppRoleApplyConfiguration {
	b.Path = &value
	return b
}

// WithRoleID sets the RoleID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleID field is set to the value of the last call.
func (b *VaultAppRoleApplyConfiguration) WithRoleID(value string) *VaultAppRoleApplyConfiguration {
	b.RoleID = &value
	return b
}

// WithRoleRef sets the RoleRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleRef field is set to the value of the last call.
func (b *VaultAppRoleApplyConfiguration) WithRoleRef(value metav1.SecretKeySelector) *VaultAppRoleApplyConfiguration {
	b.RoleRef = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *VaultAppRoleApplyConfiguration) WithSecretRef(value metav1.SecretKeySelector) *VaultAppRoleApplyConfiguration {
	b.SecretRef = &value
	return b
}
