/*
Copyright © The ESO Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

// YandexCertificateManagerProviderApplyConfiguration represents a declarative configuration of the YandexCertificateManagerProvider type for use
// with apply.
//
// YandexCertificateManagerProvider Configures a store to sync secrets using the Yandex Certificate Manager provider.
type YandexCertificateManagerProviderApplyConfiguration struct {
	// Yandex.Cloud API endpoint (e.g. 'api.cloud.yandex.net:443')
	APIEndpoint *string `json:"apiEndpoint,omitempty"`
	// Auth defines the information necessary to authenticate against Yandex.Cloud
	Auth *YandexAuthApplyConfiguration `json:"auth,omitempty"`
	// The provider for the CA bundle to use to validate Yandex.Cloud server certificate.
	CAProvider *YandexCAProviderApplyConfiguration `json:"caProvider,omitempty"`
	// FetchingPolicy configures the provider to interpret the `data.secretKey.remoteRef.key` field in ExternalSecret as certificate ID or certificate name
	FetchingPolicy *FetchingPolicyApplyConfiguration `json:"fetching,omitempty"`
}

// YandexCertificateManagerProviderApplyConfiguration constructs a declarative configuration of the YandexCertificateManagerProvider type for use with
// apply.
func YandexCertificateManagerProvider() *YandexCertificateManagerProviderApplyConfiguration {
	return &YandexCertificateManagerProviderApplyConfiguration{}
}

// WithAPIEndpoint sets the APIEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIEndpoint field is set to the value of the last call.
func (b *YandexCertificateManagerProviderApplyConfiguration) WithAPIEndpoint(value string) *YandexCertificateManagerProviderApplyConfiguration {
	b.APIEndpoint = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *YandexCertificateManagerProviderApplyConfiguration) WithAuth(value *YandexAuthApplyConfiguration) *YandexCertificateManagerProviderApplyConfiguration {
	b.Auth = value
	return b
}

// WithCAProvider sets the CAProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CAProvider field is set to the value of the last call.
func (b *YandexCertificateManagerProviderApplyConfiguration) WithCAProvider(value *YandexCAProviderApplyConfiguration) *YandexCertificateManagerProviderApplyConfiguration {
	b.CAProvider = value
	return b
}

// WithFetchingPolicy sets the FetchingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FetchingPolicy field is set to the value of the last call.
func (b *YandexCertificateManagerProviderApplyConfiguration) WithFetchingPolicy(value *FetchingPolicyApplyConfiguration) *YandexCertificateManagerProviderApplyConfiguration {
	b.FetchingPolicy = value
	return b
}
