apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: beyondtrustworkloadcredentials-ss
  namespace: external-secrets
spec:
  provider:
    beyondtrustworkloadcredentials:
      auth:
        apikey:
          token:
            name: bts-api-token
            key: token
      server:
        apiUrl: "https://api.beyondtrust.io/site"
        siteId: <SITE_ID>
      folderPath: <FOLDER_PATH>
