//go:build !ignore_autogenerated

/*
Copyright © 2025 ESO Maintainer Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import (
	"github.com/external-secrets/external-secrets/apis/externalsecrets/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManager) DeepCopyInto(out *SecretsManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManager.
func (in *SecretsManager) DeepCopy() *SecretsManager {
	if in == nil {
		return nil
	}
	out := new(SecretsManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretsManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagerList) DeepCopyInto(out *SecretsManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretsManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagerList.
func (in *SecretsManagerList) DeepCopy() *SecretsManagerList {
	if in == nil {
		return nil
	}
	out := new(SecretsManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretsManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagerSpec) DeepCopyInto(out *SecretsManagerSpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	if in.AdditionalRoles != nil {
		in, out := &in.AdditionalRoles, &out.AdditionalRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionTags != nil {
		in, out := &in.SessionTags, &out.SessionTags
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				**out = **in
			}
		}
	}
	if in.SecretsManager != nil {
		in, out := &in.SecretsManager, &out.SecretsManager
		*out = new(v1.SecretsManager)
		**out = **in
	}
	if in.TransitiveTagKeys != nil {
		in, out := &in.TransitiveTagKeys, &out.TransitiveTagKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagerSpec.
func (in *SecretsManagerSpec) DeepCopy() *SecretsManagerSpec {
	if in == nil {
		return nil
	}
	out := new(SecretsManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsManagerStatus) DeepCopyInto(out *SecretsManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsManagerStatus.
func (in *SecretsManagerStatus) DeepCopy() *SecretsManagerStatus {
	if in == nil {
		return nil
	}
	out := new(SecretsManagerStatus)
	in.DeepCopyInto(out)
	return out
}
