{{- if and .Values.v2.enabled .Values.providers.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-provider-tls
  namespace: {{ template "external-secrets.namespace" . }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
    app.kubernetes.io/component: provider-certificates
{{- end }}
