//Copyright External Secrets Inc. All Rights Reserved

package constants

const (
	ProviderAWSSM                = "AWS/SecretsManager"
	CallAWSSMGetSecretValue      = "GetSecretValue"
	CallAWSPSGetParametersByPath = "GetParametersByPath"
	CallAWSSMDescribeSecret      = "DescribeSecret"
	CallAWSSMDeleteSecret        = "DeleteSecret"
	CallAWSSMCreateSecret        = "CreateSecret"
	CallAWSSMPutSecretValue      = "PutSecretValue"
	CallAWSSMListSecrets         = "ListSecrets"

	ProviderAWSPS                = "AWS/ParameterStore"
	CallAWSPSGetParameter        = "GetParameter"
	CallAWSPSPutParameter        = "PutParameter"
	CallAWSPSDeleteParameter     = "DeleteParameter"
	CallAWSPSDescribeParameter   = "DescribeParameter"
	CallAWSPSListTagsForResource = "ListTagsForResource"

	ProviderAzureKV              = "Azure/KeyVault"
	CallAzureKVGetKey            = "GetKey"
	CallAzureKVDeleteKey         = "DeleteKey"
	CallAzureKVImportKey         = "ImportKey"
	CallAzureKVGetSecret         = "GetSecret"
	CallAzureKVGetSecrets        = "GetSecrets"
	CallAzureKVDeleteSecret      = "DeleteSecret"
	CallAzureKVGetCertificate    = "GetCertificate"
	CallAzureKVDeleteCertificate = "DeleteCertificate"
	CallAzureKVImportCertificate = "ImportCertificate"

	ProviderGCPSM                = "GCP/SecretManager"
	CallGCPSMGetSecret           = "GetSecret"
	CallGCPSMDeleteSecret        = "DeleteSecret"
	CallGCPSMCreateSecret        = "CreateSecret"
	CallGCPSMUpdateSecret        = "UpdateSecret"
	CallGCPSMAccessSecretVersion = "AccessSecretVersion"
	CallGCPSMAddSecretVersion    = "AddSecretVersion"
	CallGCPSMListSecrets         = "ListSecrets"
	CallGCPSMGenerateSAToken     = "GenerateServiceAccountToken"
	CallGCPSMGenerateIDBindToken = "GenerateIDBindToken"
	CallGCPSMGenerateAccessToken = "GenerateAccessToken"

	ProviderHCVault            = "HashiCorp/Vault"
	CallHCVaultLogin           = "Login"
	CallHCVaultRevokeSelf      = "RevokeSelf"
	CallHCVaultLookupSelf      = "LookupSelf"
	CallHCVaultReadSecretData  = "ReadSecretData"
	CallHCVaultWriteSecretData = "WriteSecretData"
	CallHCVaultDeleteSecret    = "DeleteSecret"
	CallHCVaultListSecrets     = "ListSecrets"

	ProviderKubernetes                         = "Kubernetes"
	CallKubernetesGetSecret                    = "GetSecret"
	CallKubernetesListSecrets                  = "ListSecrets"
	CallKubernetesCreateSecret                 = "CreateSecret"
	CallKubernetesDeleteSecret                 = "DeleteSecret"
	CallKubernetesUpdateSecret                 = "UpdateSecret"
	CallKubernetesCreateSelfSubjectRulesReview = "CreateSelfSubjectRulesReview"

	ProviderIBMSM                = "IBM/SecretsManager"
	CallIBMSMGetSecret           = "GetSecret"
	CallIBMSMListSecrets         = "ListSecrets"
	CallIBMSMGetSecretByNameType = "GetSecretByNameType"

	ProviderWebhook    = "Webhook"
	CallWebhookHTTPReq = "HTTPRequest"

	ProviderGitLab                 = "GitLab"
	CallGitLabListProjectsGroups   = "ListProjectsGroups"
	CallGitLabProjectVariableGet   = "ProjectVariableGet"
	CallGitLabProjectListVariables = "ProjectVariablesList"
	CallGitLabGroupGetVariable     = "GroupVariableGet"
	CallGitLabGroupListVariables   = "GroupVariablesList"

	ProviderAKEYLESSSM                  = "AKEYLESSLESS/SecretsManager"
	CallAKEYLESSSMGetSecretValue        = "GetSecretValue"
	CallAKEYLESSSMDescribeItem          = "DescribeItem"
	CallAKEYLESSSMListItems             = "ListItems"
	CallAKEYLESSSMAuth                  = "Auth"
	CallAKEYLESSSMGetRotatedSecretValue = "GetRotatedSecretValue"
	CallAKEYLESSSMGetCertificateValue   = "GetCertificateValue"
	CallAKEYLESSSMGetDynamicSecretValue = "GetDynamicSecretsValue"

	StatusError   = "error"
	StatusSuccess = "success"

	WellKnownLabelKey             = "external-secrets.io/component"
	WellKnownLabelValueController = "controller"
	WellKnownLabelValueWebhook    = "webhook"
)
