name: CRDs

on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'
  pull_request:
    paths:
      - 'apis/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crd-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Generate crds for testing
        run: make crds.generate.tests

      - name: Run crd tests
        run: make test.crds
