name: CRDs

on:
  push:
    branches:
      - main
    paths:
      - 'apis/**'
  pull_request:
    paths:
      - 'apis/**'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  crd-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate crds for testing
        run: make crds.generate.tests

      - name: Run crd tests
        run: make test.crds
