name: Dependency License Checks

on:
  pull_request:
    paths:
      - "go.mod"
  workflow_dispatch: {}

permissions:
  contents: read

env:
  HAS_FOSSA_KEY: ${{ secrets.FOSSA_API_KEY != '' }}

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        with:
          egress-policy: audit
      - name: "Checkout Code"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        with:
          persist-credentials: false

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # main
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        with:
          api-key: ${{ env.FOSSA_API_KEY }}

      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # main
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        with:
          api-key: ${{ env.FOSSA_API_KEY }}
          run-tests: true
