name: Dependency License Checks

on:
  pull_request:
    paths:
      - "go.mod"
  workflow_dispatch: {}

permissions:
  contents: read

env:
  HAS_FOSSA_KEY: ${{ secrets.FOSSA_API_KEY != '' }}

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        with:
          egress-policy: audit
      - name: "Checkout Code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        with:
          persist-credentials: false

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # main
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        with:
          api-key: ${{ env.FOSSA_API_KEY }}

      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # main
        if: ${{ env.HAS_FOSSA_KEY == 'true' }}
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        with:
          api-key: ${{ env.FOSSA_API_KEY }}
          run-tests: true
