name: Update dependencies

on:
  schedule:
    # Monday, 10AM UTC
    - cron: "0 10 * * 1"
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      # The default token does not trigger workflows on the resulting PR.
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        env:
          APP_ID: ${{ secrets.APP_ID }}
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.repository }}
          permission-contents: write
          permission-pull-requests: write
          permission-workflows: write

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Publish dependency updates
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          UPDATECLI_PUBLISH: "true"
        run: make update-deps
