name: Update dependencies

on:
  schedule:
    # Monday, 10AM UTC
    - cron: "0 10 * * 1"
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      # The default token does not trigger workflows on the resulting PR.
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        env:
          APP_ID: ${{ secrets.APP_ID }}
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          git config --global user.email "ExternalSecretsOperator@users.noreply.github.com"
          git config --global user.name "External Secrets Operator"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GH_REPO}.git"

          make update-deps
          if git diff-index --quiet HEAD --; then
            echo "nothing changed. skipping."
            exit 0
          fi

          git checkout -B update-deps
          git add -A
          git commit -m "update dependencies" -s
          make check-diff
          git push --force-with-lease origin update-deps
          gh pr view update-deps >/dev/null 2>&1 || \
            gh pr create --base main --head update-deps --title 'chore: update dependencies' --body 'Update dependencies'
